- 도

- 시군구 코드

- 읍면동 코드

- 평일(주말)

- 전체

- 승용

- 버스

- 화물

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
plt.rc('font', family = 'malgun Gothic')
%matplotlib inline
import warnings

In [34]:
traffic_1 = pd.read_excel('01월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_2 = pd.read_excel('02월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_3 = pd.read_excel('03월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_4 = pd.read_excel('04월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_5 = pd.read_excel('05월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_6 = pd.read_excel('06월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_7 = pd.read_excel('07월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_8 = pd.read_excel('08월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_9 = pd.read_excel('09월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_10 = pd.read_excel('10월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_11= pd.read_excel('11월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
traffic_12 = pd.read_excel('12월 서울시 교통량 조사자료(2023).xlsx', sheet_name=1)
speed = pd.read_excel('2023_차속도_1월.xlsx')
code = pd.read_excel('12월 서울시 교통량 조사자료(2023).xlsx', sheet_name=2)

-교통량에 대한 전체적인 데이터 합본 하는 과정

In [70]:
speed.iloc[:,:11].head(5)

,일자,요일,도로명,링크아이디,시점명,종점명,방향,거리,차선수,기능유형구분,도심/외곽구분
0,20230101,일,4.19로,1080012200,아카데미하우스,국립4.19묘지,상행,1179,1.0,보조간선도로,외곽
1,20230101,일,4.19로,1080012800,국립4.19묘지,국립4.19묘지입구,상행,352,2.0,보조간선도로,외곽
2,20230101,일,4.19로,1080012700,국립4.19묘지입구,국립4.19묘지,하행,354,2.0,보조간선도로,외곽
3,20230101,일,4.19로,1080012100,국립4.19묘지,아카데미하우스,하행,1190,1.0,보조간선도로,외곽
4,20230101,일,가락로,1230024700,방이초교,방이동고분군,상행,844,1.0,기타도로,외곽

In [35]:
traffic = pd.concat([traffic_1,traffic_2,traffic_3,traffic_4,traffic_5,traffic_6,traffic_7,traffic_8,traffic_9,traffic_10,
                     traffic_11,traffic_12], axis = 0);traffic

,일자,요일,지점명,지점번호,방향,구분,0시,1시,2시,3시,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,요일(2)
0,20230101,일,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,564.0,414.0,268.0,208.0,...,1370.0,1322.0,1263.0,979.0,875.0,785.0,824.0,552.0,421.0,NaN
1,20230102,월,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,294.0,190.0,146.0,134.0,...,1571.0,1566.0,1792.0,1582.0,1248.0,997.0,973.0,872.0,616.0,NaN
2,20230103,화,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,419.0,271.0,203.0,177.0,...,1678.0,1711.0,1851.0,1697.0,1265.0,1081.0,1090.0,883.0,757.0,NaN
3,20230104,수,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,502.0,335.0,247.0,192.0,...,1798.0,1719.0,1807.0,1679.0,1240.0,1112.0,1069.0,909.0,769.0,NaN
4,20230105,목,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,523.0,334.0,235.0,196.0,...,1627.0,1805.0,1798.0,1770.0,1289.0,1152.0,1111.0,1030.0,756.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,20231227,수,신월여의지하도로,F-10,유출,서울교->신월IC,629.0,391.0,288.0,174.0,...,2012.0,2176.0,2109.0,2060.0,2082.0,2171.0,1726.0,1686.0,853.0,NaN
8614,20231228,목,신월여의지하도로,F-10,유출,서울교->신월IC,652.0,467.0,284.0,199.0,...,2127.0,2180.0,2085.0,2046.0,2112.0,1972.0,1756.0,1760.0,1216.0,NaN
8615,20231229,금,신월여의지하도로,F-10,유출,서울교->신월IC,811.0,536.0,363.0,243.0,...,2210.0,2090.0,2026.0,1903.0,2071.0,2049.0,1679.0,1604.0,1278.0,NaN
8616,20231230,토,신월여의지하도로,F-10,유출,서울교->신월IC,793.0,571.0,339.0,296.0,...,1646.0,1832.0,1615.0,1434.0,1294.0,1350.0,1180.0,1106.0,594.0,NaN
8617,20231231,일,신월여의지하도로,F-10,유출,서울교->신월IC,484.0,335.0,273.0,194.0,...,1837.0,2035.0,1862.0,1738.0,1400.0,1425.0,1409.0,1173.0,721.0,NaN

In [36]:
traffic['날짜'] = pd.to_datetime(traffic['일자'],format = '%Y%M%d')
traffic['month'] = traffic['날짜'].dt.month
traffic['year'] = traffic['날짜'].dt.year

In [37]:
traffic.columns

Index(['일자', '요일', '지점명', '지점번호', '방향', '구분', '0시', '1시', '2시', '3시', '4시',
       '5시', '6시', '7시', '8시', '9시', '10시', '11시', '12시', '13시', '14시', '15시',
       '16시', '17시', '18시', '19시', '20시', '21시', '22시', '23시', '요일(2)', '날짜',
       'month', 'year'],
      dtype='object')

In [38]:
df = traffic.groupby(['지점명','방향'])[['0시', '1시', '2시', '3시', '4시',
       '5시', '6시', '7시', '8시', '9시', '10시', '11시', '12시', '13시', '14시', '15시',
       '16시', '17시', '18시', '19시', '20시', '21시', '22시', '23시']].sum().T.sum()

In [39]:
car = pd.DataFrame(df, columns = ['교통량'])

In [40]:
car['year'] = 2024
car['month'] = 1
car = car.reset_index();car

               지점명  방향         교통량  year  month
0             가양대교  유입  20150186.0  2024      1
1             가양대교  유출  17853431.0  2024      1
2    강남대로(강남역-신분당)  유입   9029824.0  2024      1
3    강남대로(강남역-신분당)  유출   9620604.0  2024      1
4        강남대로(신사역)  유입  13078683.0  2024      1
..             ...  ..         ...   ...    ...
275      화랑로(상월곡역)  유출   9713602.0  2024      1
276      화랑로(조선왕릉)  유입   8170713.0  2024      1
277      화랑로(조선왕릉)  유출   8530736.0  2024      1
278      화랑로(화랑대역)  유입  10148959.0  2024      1
279      화랑로(화랑대역)  유출  10278999.0  2024      1

[280 rows x 5 columns]

In [51]:
code_cnt = code.copy()
code_cnt = code_cnt[['지점명칭','위도','경도']]
code_cnt.rename(columns = {'지점명칭':'지점명'}, inplace=True)

In [52]:
car = car.merge(code_cnt, on = '지점명');car

               지점명  방향         교통량  year  month         위도          경도
0             가양대교  유입  20150186.0  2024      1  37.571567  126.862726
1             가양대교  유출  17853431.0  2024      1  37.571567  126.862726
2    강남대로(강남역-신분당)  유입   9029824.0  2024      1  37.490590  127.031160
3    강남대로(강남역-신분당)  유출   9620604.0  2024      1  37.490590  127.031160
4        강남대로(신사역)  유입  13078683.0  2024      1  37.514859  127.020098
..             ...  ..         ...   ...    ...        ...         ...
267      화랑로(상월곡역)  유출   9713602.0  2024      1  37.603932  127.044044
268      화랑로(조선왕릉)  유입   8170713.0  2024      1  37.630725  127.098984
269      화랑로(조선왕릉)  유출   8530736.0  2024      1  37.630725  127.098984
270      화랑로(화랑대역)  유입  10148959.0  2024      1  37.619936  127.082950
271      화랑로(화랑대역)  유출  10278999.0  2024      1  37.619936  127.082950

[272 rows x 7 columns]

In [54]:
car = car.groupby(['지점명']).agg({'교통량':'sum','위도':'mean','경도':'mean','year':'mean','month':'mean'}).reset_index()
car.to_csv('교통량_2023.csv', encoding = 'cp949', index=False)

In [55]:
p = pd.read_excel('교통량_2023.xlsx')
p.dropna().reset_index(drop=True).to_csv("교통량_2023_마무리.csv", encoding = 'cp949',index = False)

In [44]:
code.head(3)

,지점번호,지점명칭,검지기 유형,위도,경도,주소,도로명 주소,유입 방향,유출방향
0,A-01,성산로(금화터널),지자기,37.568588,126.948436,서울시 서대문구 신촌동 1-142,NaN,[성산로]봉원고가차도->독립문역,[성산로]독립문역->봉원고가차도
1,A-02,사직로(사직터널),지자기,37.572298,126.962853,서울시 종로구 행촌동 1-186,NaN,[사직로]독립문역->사직단,[사직로]사직단->독립문역
2,A-03,자하문로(자하문터널),지자기,37.588831,126.968548,서울시 종로구 청운동 24-6,NaN,[자하문로]석파정->청운초등학교,[자하문로]청운초등학교->석파정

공사장 관련 지수 산출과정

In [196]:
fac = pd.read_csv('factory_23.csv',encoding = 'utf-8') ;fac.head(3)

,Unnamed: 0,번호,사업자명(상호),공사장명,소재지도로명주소,소재지지번주소,관리기관명,데이터기준일자(신고일자),설치(공사)시작일,설치(공사)종료일,발생사업명,종료_year,종료_month,시작_year,시작_month
0,0,1,(주)계룡건설산업,경부선 원효가도교 개량공사,"서울특별시 용산구 한강대로77길 25, 남영역 (갈월동)",서울특별시 용산구 갈월동 96-1 남영역,서울특별시 용산구,2023-02-01,2023-03-31,2026-07-17,건설업,2026,7,2023,3
1,1,2,도시건축종합건설(주),재동 32-10 근린생활시설 신축공사,서울특별시 종로구 재동 32-10,서울특별시 종로구 재동 32-10,서울특별시 종로구,2023-05-16,2023-06-01,2024-07-31,건설업,2024,7,2023,6
2,2,3,(주)쿤스트종합건설,대치동 891-53 업무시설 및 근린생활시설 신축공사,X,서울특별시 강남구 대치동 891-53,서울특별시 강남구,2023-05-16,2021-07-26,2023-11-30,X,2023,11,2021,7

위도, 경도에 대한 정보를 얻기 위한 코드

In [1]:
import requests
import json
def parcel_json_requester(road):
    apiurl = "https://api.vworld.kr/req/address?"
    params = {
        "service": "address",
        "request": "getcoord",
#        "crs": "epsg:3857",
        "address": road,
        "format": "json",
        "type": "PARCEL",
        "key": "없앰"
    }
    response = requests.get(apiurl, params=params)
    if response.status_code == 200:
        return response.json()

def road_json_requester(road):
    apiurl = "https://api.vworld.kr/req/address?"
    params = {
        "service": "address",
        "request": "getcoord",
#        "crs": "epsg:3857",
        "address": road,
        "format": "json",
        "type": "road",
        "key": "없앰"
    }
    response = requests.get(apiurl, params=params)
    if response.status_code == 200:
        return response.json()

def geocoder_parcel(road):
    geocode = (None, None)
    json_data = parcel_json_requester(road)
    if json_data['response']['status'] == 'NOT_FOUND' or json_data['response']['status'] == 'ERROR':
        return geocode

    x = json_data['response']['result']['point']['x']
    y = json_data['response']['result']['point']['y']

    geocode = (float(y), float(x))
    return geocode

def geocoder_road(road):
    geocode = (None, None)
    json_data = road_json_requester(road)
    if json_data['response']['status'] == 'NOT_FOUND' or json_data['response']['status'] == 'ERROR':
        return geocode

    x = json_data['response']['result']['point']['x']
    y = json_data['response']['result']['point']['y']

    geocode = (float(y), float(x))
    return geocode

In [208]:
fac.head(3)

,Unnamed: 0,번호,사업자명(상호),공사장명,소재지도로명주소,소재지지번주소,관리기관명,데이터기준일자(신고일자),설치(공사)시작일,설치(공사)종료일,발생사업명,종료_year,종료_month,시작_year,시작_month,위도,경도
0,0,1,(주)계룡건설산업,경부선 원효가도교 개량공사,"서울특별시 용산구 한강대로77길 25, 남영역 (갈월동)",서울특별시 용산구 갈월동 96-1 남영역,서울특별시 용산구,2023-02-01,2023-03-31,2026-07-17,건설업,2026,7,2023,3,1.949279e+06,953288.316265
1,1,2,도시건축종합건설(주),재동 32-10 근린생활시설 신축공사,서울특별시 종로구 재동 32-10,서울특별시 종로구 재동 32-10,서울특별시 종로구,2023-05-16,2023-06-01,2024-07-31,건설업,2024,7,2023,6,1.953444e+06,954462.222817
2,2,3,(주)쿤스트종합건설,대치동 891-53 업무시설 및 근린생활시설 신축공사,X,서울특별시 강남구 대치동 891-53,서울특별시 강남구,2023-05-16,2021-07-26,2023-11-30,X,2023,11,2021,7,1.945148e+06,960650.555789

In [209]:
fac['소재지도로명주소'].value_counts()

소재지도로명주소
X                                      477
서울특별시 마포구 월드컵로 212, 마포구청 (성산동)           5
서울특별시 관악구 관악로 1, 서울대학교 (신림동)             3
서울특별시 금천구 가산디지털1로 205-28(가산동)            3
도봉구 관내                                   3
                                      ...
동대문구 관내 이면도로 일대                          1
서울특별시 서초구 서초동 1554-2 외 6필지               1
서울특별시 서대문구 가재울로 45(남가좌동, 남가좌동현대아파트)      1
서울특별시 서대문구 수색로4길 14(남가좌동)                1
서울특별시 노원구 공릉2동 산223-19 외 5필지             1
Name: count, Length: 1040, dtype: int64

In [227]:
latitude,longitude = [],[]
for x in fac['소재지도로명주소']:
    print(x, end = '')
    (lat,lng) = geocoder_road(x)
    print('위도 : %s | 경도 : %s' %(lat,lng))
    latitude.append(lat)
    longitude.append(lng)

서울특별시 용산구 한강대로77길 25, 남영역 (갈월동)위도 : 37.54045664 | 경도 : 126.971332797
서울특별시 종로구 재동 32-10위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 광진구 중곡동 158-7~중곡동16위도 : None | 경도 : None
서울특별시 금천구 벚꽃로 244(가산동)위도 : 37.47673913 | 경도 : 126.885826446
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 마포구 성미산로 112 (연남동)위도 : 37.562085088 | 경도 : 126.9195745
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 동작구 여의대방로10길 100 (신대방동, 숲속마을 신동아 파밀리에)위도 : 37.492040778 | 경도 : 126.914705159
서울특별시 종로구 평창문화로 130, 귀빈빌딩 (평창동)위도 : 37.609090757 | 경도 : 126.974566322
서울특별시 양천구 목동남로4길 6-46 (신정동, 목동2차우성아파트)위도 : 37.506731076 | 경도 : 126.864796631
서울특별시 양천구 오목로 337-6 (목동)위도 : None | 경도 : None
서울특별시 양천구 목동중앙북로7가길 61 (목동, 목동 RICH SQUARE) 외위도 : 37.549728879 | 경도 : 126.864177516
서울특별시 종로구 필운동 142-7 ~ 내자동 235-3위도 : None | 경도 : None
서울특별시 용산구 원효로 227, 원효로우체국빌딩 (원효로1가)위도 : 37.538636886 | 경도 : 126.966806663
서울특별시 광진구 아차산로69길 29 (광장동, 광장11차 현대홈타운)위도 : 37.542756697 | 경도 : 127.097078521
서울특별시 영등포구 문래북로 83, 제이씨 빌딩 (당산동2가)위도 : 37.520477886 | 경도 : 126.894510863
서울특별시 서초구 서초동 1649-16 주변 외 5개소위도 : None | 경도 : None
관악구 봉천동 1637-27위도 : None | 경도 : None
서울특별시 동작구 여의대방로22아길 22(신대방동, 신동아아파트)위도 : 37.496602439 | 경도 : 126.924067824
서울특별시 동작구 서달로 61 일원위도 : 37.499574777 | 경도 : 126.960156192
궁동110-1 외 5필지위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
오류동 108-24위도 : None | 경도 : None
오류동 217-51 외 1필지위도 : None | 경도 : None
서울특별시 서초구 강남대로 186, 준영빌딩 (양재동)위도 : None | 경도 : None
서울특별시 서대문구 수색로 102(북가좌동, DMC요진아파트)위도 : 37.572845976 | 경도 : 126.908283296
X위도 : 37.537798161 | 경도 : 127.211875874
도림로3길주변(구로동로100 외 9개소)위도 : None | 경도 : None
구로동로20길 주변(구로동로18길19 외7개소)위도 : 37.488065631 | 경도 : 126.887639799
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 성동구 가람길 283(용답동)위도 : None | 경도 : None
서울특별시 노원구 동일로 1107, 엘지전자 베스트샵 공릉점 (공릉동)위도 : 37.628548341 | 경도 : 127.071098984
삼양로 159길 24 ~ 삼양로 163길 13 외10개소(관내)위도 : 37.658058591 | 경도 : 127.012515098
서울특별시 성북구 한천로 592-5 (석관동, 모던하우스)위도 : 37.612382016 | 경도 : 127.061629009
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 노원구 상계로7길 18 (상계동, 우성아파트)위도 : 37.658175704 | 경도 : 127.064827255
서울특별시 서초구 서초동 1592-10위도 : None | 경도 : None
서울특별시 서초구 서초동 1335-2 ~ 서초동 1603-55위도 : None | 경도 : None
서울특별시 서대문구 남가좌동 290번지 일대위도 : None | 경도 : None
서울특별시 동대문구 답십리로 252 (장안동)위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울 서대문구 대현동 56-5위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 동대문구 안암로 132 (제기동)위도 : 37.586839753 | 경도 : 127.033493603
X위도 : 37.537798161 | 경도 : 127.211875874
봉천동 180-311위도 : None | 경도 : None
봉천동 180-255위도 : None | 경도 : None
봉천동 180-5위도 : None | 경도 : None
서울특별시 중구 서애로1길 17 (묵정동)위도 : None | 경도 : None
서울특별시 중구 다산로40길 33-8 (신당동)위도 : 37.563862487 | 경도 : 127.018270167
서울특별시 마포구 상암산로1길 24 (상암동, 상암 월드컵파크 4단지)위도 : 37.578202268 | 경도 : 126.889922831
서울특별시 강서구 가로공원로 236-4 (화곡동, 골든빌) 외 4개소위도 : 37.538065041 | 경도 : 126.842019223
삼양로123길 일대위도 : 37.644774875 | 경도 : 127.015421642
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
마곡동 762-2위도 : None | 경도 : None
서울특별시 동작구 사당로 165(사당동, 대아아파트)위도 : 37.487428461 | 경도 : 126.967889042
서울특별시 강서구 화곡로43가길 31 (화곡동)위도 : 37.548097674 | 경도 : 126.844222669
서울특별시 종로구 우정국로 65-8 (견지동)위도 : 37.574863282 | 경도 : 126.982362302
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 영등포구 대림동 706-4~1031-2번지 외 16개소위도 : None | 경도 : None
서울특별시 관악구 남부순환로 1578 (신림동)위도 : 37.48348562 | 경도 : 126.925928095
서울특별시 관악구 남부순환로 1588, 신림빌딩 (신림동)위도 : 37.483665463 | 경도 : 126.927065849
서울특별시 동대문구 답십리로 288, 아트몰링 장안 (장안동)위도 : 37.571934338 | 경도 : 127.072354149
서울특별시 동대문구 왕산로33길 78 (제기동)위도 : None | 경도 : None
서울특별시 성동구 성수일로12길 33(성수동2가)위도 : 37.547733181 | 경도 : 127.054654681
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 노원구 상계동 656 외 1필지 상계주공11단지 아파트위도 : None | 경도 : None
서울특별시 광진구 면목로 62, ~104 주변 (중곡동)위도 : 37.559346324 | 경도 : 127.077807926
서울특별시 광진구 면목로 167, 일대 (중곡동)위도 : 37.568153225 | 경도 : 127.082301807
서울시 광진구 일대위도 : None | 경도 : None
서울특별시 마포구 양화로7안길 42(서교동)위도 : 37.553485522 | 경도 : 126.915313846
서울특별시 서대문구 통일로 384, 독립문주유소 (홍제동)위도 : 37.58414508 | 경도 : 126.949537023
서울특별시 은평구 역말로 7길 3-9위도 : 37.606381146 | 경도 : 126.917756287
서울특별시 영등포구 가마산로 442(신길동, 래미안프레비뉴)위도 : 37.504997582 | 경도 : 126.909349954
서울특별시 중구 청구로6길 61(신당동)위도 : 37.56262939 | 경도 : 127.015803842
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 서초구 서초동 1478-13 외 2필지위도 : None | 경도 : None
서울특별시 서초구 서초동 1496-7위도 : None | 경도 : None
구로구오류동 33-9번지 외 1필지위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 광진구 아차산로 382(자양동)위도 : 37.53664986 | 경도 : 127.085285159
서울특별시 광진구 능동로 427(중곡동)위도 : None | 경도 : None
서울특별시 종로구 세검정로6길 62-2(신영동)위도 : 37.599981448 | 경도 : 126.962509921
서울특별시 종로구 경희궁길 27, 서울교원회관 (신문로2가)위도 : 37.572107525 | 경도 : 126.970465593
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 동작구 서달로 83(흑석동, 우리유앤미아파트)위도 : 37.500216316 | 경도 : 126.959432692
서울특별시 중구 다산로36나길 19(신당동)위도 : 37.56089445 | 경도 : 127.019929951
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 동대문구 장안벚꽃로5길 10(휘경동, 휘경 동일하이빌)위도 : 37.582564155 | 경도 : 127.073605029
서울특별시 관악구 양녕로6길 1(봉천동)위도 : 37.484788879 | 경도 : 126.946958114
서울특별시 용산구 원효로 150(원효로3가)위도 : 37.534308149 | 경도 : 126.959708823
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 송파구 양재대로 932, 가락동 농수산물도매시장 (가락동)위도 : 37.493810321 | 경도 : 127.11289193
장충단로4길 일대위도 : 37.561307407 | 경도 : 127.006886343
서울특별시 광진구 아차산로 549(광장동, 광장현대파크빌)위도 : 37.544523154 | 경도 : 127.102516309
서울특별시 중구 퇴계로73가길 10(신당동)위도 : 37.565888681 | 경도 : 127.013728366
구로동로20길 주변(구로동로18길19 외7개소)위도 : 37.488065631 | 경도 : 126.887639799
서울특별시 양천구 목동동로 100 (신정동, 목동신시가지아파트13단지)위도 : 37.513428606 | 경도 : 126.863722459
서울특별시 서초구 서초동 1699-6위도 : None | 경도 : None
서울특별시 서초구 서초동 1588-6위도 : None | 경도 : None
서울특별시 관악구 미성길 122(신림동, 신림동쌍용아파트)위도 : 37.472315257 | 경도 : 126.911923037
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 광진구 천호대로 576(능동)위도 : 37.55589605 | 경도 : 127.081835818
서울특별시 구로구 신도림동 330-42 외 15필지위도 : None | 경도 : None
서울특별시 동대문구 한천로2길 73(장안동)위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 동작구 노량진로17길 12(노량진동)위도 : 37.513087546 | 경도 : 126.943228368
서울특별시 강서구 공항대로81길 12(염창동, 덕수연립)위도 : 37.547897835 | 경도 : 126.876812507
서울특별시 강서구 곰달래로24길 18, 남흥빌딩 (화곡동)위도 : 37.529799421 | 경도 : 126.846940005
서울특별시 중구 퇴계로8길 49-7 (회현동1가)위도 : None | 경도 : None
서울특별시 중구 퇴계로8길 49-7 (회현동1가)위도 : None | 경도 : None
한천로80길 일대위도 : 37.611589571 | 경도 : 127.063222372
서울특별시 용산구 한강로3가 98-4 일원위도 : None | 경도 : None
서울특별시 동작구 성대로6사길 39(상도동, 풀하우스 2차)위도 : 37.49353061 | 경도 : 126.936832773
서울특별시 동작구 성대로6사길 37(상도동, 풀하우스 1차)위도 : 37.493482861 | 경도 : 126.936988053
서울특별시 금천구 시흥대로2길 60-15(시흥동)위도 : 37.434517248 | 경도 : 126.906895474
서울특별시 강동구 양재대로91나길 36 인근위도 : 37.527021481 | 경도 : 127.131700781
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 노원구 동일로 1039 (공릉동)위도 : 37.622890317 | 경도 : 127.073592657
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 광진구 천호대로 621 (중곡동)위도 : 37.554701787 | 경도 : 127.086759395
서울특별시 광진구 자양동 뚝섬로 596~630 외 1구간위도 : 37.532958731 | 경도 : 127.075934554
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 금천구 시흥대로101길 3-18 (독산동, 철매아파트)위도 : 37.463843174 | 경도 : 126.895972014
서울특별시 강서구 곰달래로31가길 27, 신정초등학교 (화곡동) 주변 일대위도 : 37.532578017 | 경도 : 126.852420177
서울특별시 성동구 동일로43가길(송정동)위도 : 37.55416894 | 경도 : 127.07026405
서울특별시 성동구 연무장18길 4(성수동2가)위도 : 37.540309588 | 경도 : 127.060974459
서울특별시 성동구 광나루로11길 27-1(송정동)위도 : 37.550393959 | 경도 : 127.066935403
서울특별시 용산구 한강대로 142(한강로2가)위도 : 37.53189538 | 경도 : 126.970817595
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 성북구 아리랑로5길 25 (동소문동7가, 브라운스톤동선)위도 : 37.596506684 | 경도 : 127.013493052
서울특별시 마포구 독막로 16(합정동)위도 : 37.548441479 | 경도 : 126.915105387
서울특별시 강서구 허준로 76(가양동, 한보구암마을아파트)위도 : 37.56841414 | 경도 : 126.848657286
서울특별시 종로구 관수동 59-7위도 : None | 경도 : None
서울특별시 종로구 세검정로6길 54 (신영동, 목련빌라)위도 : 37.599945976 | 경도 : 126.962136118
서울특별시 서대문구 홍제동 53-3 일대위도 : None | 경도 : None
이문로46길 주변 외위도 : 37.601781256 | 경도 : 127.062764802
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 영등포구 당산로 187, 당서초등학교 (당산동5가)위도 : 37.532035898 | 경도 : 126.899796238
서울특별시 영등포구 도신로29길 28 (영등포동, 영등포푸르지오)위도 : 37.512509046 | 경도 : 126.902413287
서울특별시 중구 을지로 133-1 (을지로3가)위도 : None | 경도 : None
서울특별시 양천구 국회대로 78(신월동)위도 : 37.526684417 | 경도 : 126.84367846
서울특별시 강남구 개포로15길 8(개포동)위도 : 37.479009073 | 경도 : 127.045481617
X위도 : 37.537798161 | 경도 : 127.211875874
진관4로 17위도 : 37.643890847 | 경도 : 126.923728762
서울특별시 금천구 독산로24라길 3 (시흥동)위도 : 37.454823148 | 경도 : 126.907246123
서울특별시 관악구 관악로 1, 서울대학교 (신림동)위도 : 37.468557379 | 경도 : 126.957025459
서울특별시 강서구 양천로 705(염창동)위도 : 37.550126263 | 경도 : 126.874303408
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 광진구 용마산로1길 33, 믿음교회 (중곡동)위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 금천구 범안로 1207(독산동)위도 : 37.466655669 | 경도 : 126.895810908
서울특별시 종로구 사직로10길 8, 세일빌딩 (필운동)위도 : 37.575593274 | 경도 : 126.970269892
서울특별시 종로구 종로63다길 17(숭인동)위도 : 37.57400598 | 경도 : 127.017796179
서울특별시 종로구 경희궁1길 33(신문로2가)위도 : 37.572417087 | 경도 : 126.96900586
강북구 수유동 93-1번지 외 2필지위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 강남구 논현로85길 13, 역삼동빌딩 (역삼동)위도 : 37.499058451 | 경도 : 127.036274113
광진구 관내(중곡동 일대)위도 : None | 경도 : None
서울특별시 동작구 노량진로17길 12 (노량진동)위도 : 37.513087546 | 경도 : 126.943228368
서울특별시 영등포구 신길동 1354번지위도 : None | 경도 : None
구로동644-12위도 : None | 경도 : None
개봉동 195-7 일대위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 영등포구 국회대로68길 14, 신동해빌딩 (여의도동)위도 : 37.529044625 | 경도 : 126.919301633
서울특별시 금천구 가산디지털2로 169-37(가산동)위도 : 37.481718713 | 경도 : 126.875546634
개봉동272-8, 271-4위도 : None | 경도 : None
중화동(308-88 ~ 308-69), 묵둥(247-27 ~ 247-63), 면목동(144-1 ~ 133-1)위도 : None | 경도 : None
서울특별시 영등포구 양평로30가길 15 (양평동6가, 동양아파트)위도 : 37.542476146 | 경도 : 126.890106302
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 은평구 연서로외 일원위도 : None | 경도 : None
서울특별시 마포구 토정로 55(합정동)위도 : 37.545758561 | 경도 : 126.916951139
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 중랑구 면목동 1081-1 외 3필지위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 서대문구 일원(상시변동)위도 : None | 경도 : None
서울특별시 강서구 양천로67길 15, 한희빌딩 (염창동)위도 : 37.555047716 | 경도 : 126.867519785
서울특별시 강서구 공항대로 553(염창동)위도 : 37.549981488 | 경도 : 126.86735557
서울특별시 노원구 노해로 506, 상계로3길 50, 수락산로 246, 동일로241길 84 일대위도 : 37.654845279 | 경도 : 127.064240752
서울특별시 노원구 덕릉로 700, 덕릉로 712-4, 상계로 142, 노원로30길 74 일대위도 : None | 경도 : None
서울특별시 강동구 성내로14길 18 (성내동, 선광아파트)위도 : 37.527167523 | 경도 : 127.126671955
서울특별시 서대문구 충정로 50, 골든브릿지빌딩 (충정로3가)위도 : 37.562962448 | 경도 : 126.965134911
서울특별시 영등포구 당산로30길 14(당산동3가, 대우로얄프라임)위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 중랑구 망우로 293(상봉동)위도 : 37.596546129 | 경도 : 127.08520445
서울특별시 중랑구 망우동 산58 일대위도 : None | 경도 : None
서울특별시 성동구 마조로18길 (마장동)위도 : 37.565374503 | 경도 : 127.042739252
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 종로구 통일로 256, 세란병원 (무악동)위도 : 37.575240101 | 경도 : 126.957347126
서울특별시 서초구 매헌로 99, 양재시민의숲 (양재동)위도 : 37.473082252 | 경도 : 127.036983657
서울특별시 서초구 서초동 1604-17, 18위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 양천구 목동서로 400 (신정동, 목동신시가지아파트10단지)위도 : 37.516388082 | 경도 : 126.860297932
서울특별시 금천구 가산디지털1로 205-28(가산동)위도 : None | 경도 : None
서울특별시 노원구 관내(현장사무실: 공릉동 25-23)위도 : None | 경도 : None
상계6,7동 주민센터 교차로~노원롯데백화점, 상계동 709-2위도 : None | 경도 : None
서울특별시 마포구 월드컵로 212, 마포구청 (성산동)위도 : 37.566251594 | 경도 : 126.901498209
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 서초구 사평대로22길 6, 삼영빌딩 (반포동)위도 : 37.49939662 | 경도 : 126.997378577
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 성북구 월계로 172 (장위동)위도 : 37.619259204 | 경도 : 127.044900806
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 용산구 이태원로54길 13 (한남동)위도 : 37.537730919 | 경도 : 127.002175872
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 강동구 올림픽로 지하776(암사동)위도 : 37.548022852 | 경도 : 127.127069591
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 양천구 목동서로 161 (목동)위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 동대문구 천호대로45라길 15 (용두동)위도 : 37.576896576 | 경도 : 127.043779603
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 중구 마른내로9길 10, 덕수중학교 (인현동2가)위도 : 37.565478567 | 경도 : 126.99722372
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 금천구 시흥대로73길 70(시흥동)위도 : 37.456902661 | 경도 : 126.895367606
서울특별시 종로구 세검정로9길 1, 서울세검정초등학교 (신영동)위도 : 37.603030178 | 경도 : 126.961136678
서울특별시 서대문구 응암로 28(북가좌동, DMC한양)위도 : 37.575910257 | 경도 : 126.908499301
서울특별시 금천구 시흥대로153길 23(독산동)위도 : 37.476901622 | 경도 : 126.897041321
서울특별시 금천구 가마산로 76(가산동)위도 : 37.48509271 | 경도 : 126.874961862
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 관악구 서림3길 63, 장원 (신림동)위도 : None | 경도 : None
서울특별시 종로구 율곡로 46, 서울종로경찰서 (경운동)위도 : 37.575299719 | 경도 : 126.984669293
서울특별시 종로구 진흥로21길 6(구기동)위도 : 37.608121508 | 경도 : 126.958268851
서울특별시 용산구 원효로 86, 현대자동차원효로서비스 (원효로4가)위도 : 37.531519758 | 경도 : 126.953449822
서울특별시 용산구 이태원로 148(이태원동)위도 : 37.533991798 | 경도 : 126.990365939
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 영등포구 당산로31길 6, 영등포병원 (당산동3가)위도 : 37.526729197 | 경도 : 126.896065366
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 중구 서소문로 131 (서소문동)위도 : 37.563826668 | 경도 : 126.975470652
서울특별시 용산구 우사단로14길 15 (이태원동)위도 : 37.534277439 | 경도 : 126.996555017
서울특별시 강남구 양재대로55길 12 (일원동, 수서아파트)위도 : 37.493590428 | 경도 : 127.090511559
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 관악구 난곡로34길 76(신림동, 남강빌라)위도 : None | 경도 : None
서울특별시 강동구 양재대로88길 27 (둔촌동)위도 : 37.526203092 | 경도 : 127.137478091
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 강동구 양재대로88길 27 (둔촌동)위도 : 37.526203092 | 경도 : 127.137478091
서울특별시 중구 청구로 64 (신당동, 청구 e편한세상)위도 : 37.559959916 | 경도 : 127.015450666
광진구 관내위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 서초구 서초동 1319-9위도 : None | 경도 : None
서울특별시 서초구 서초동 1685위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 성동구 자동차시장1길 104-65위도 : 37.558828635 | 경도 : 127.068376981
서울특별시 은평구 은평로 195 (은평구 관내 일대)위도 : 37.602456159 | 경도 : 126.928822743
서울특별시 금천구 한내로 69-15(독산동, 주공13단지아파트)위도 : 37.457809657 | 경도 : 126.886252312
서울특별시 동작구 여의대방로 68 (신대방동)위도 : 37.496388741 | 경도 : 126.914162219
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 양천구 목동로 224 (목동, 대원칸타빌1차아파트)위도 : 37.528384806 | 경도 : 126.864681203
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 서대문구 포방터2길 58 (홍은동)위도 : 37.596887732 | 경도 : 126.950832877
서울특별시 서초구 서초동 1554-2 외 5필지위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
미아동 233-62호외 30필지위도 : None | 경도 : None
서울특별시 마포구 와우산로29길 55 (서교동)위도 : 37.555768207 | 경도 : 126.927091607
서울특별시 동대문구 답십리65길 일대위도 : None | 경도 : None
서울특별시 중랑구 면목동 727-302외 5필지위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
서울시 동작구 노량진동 316-1 일원위도 : None | 경도 : None
서울특별시 강동구 천호대로168길 51 (성내동, 성내1차이편한세상)위도 : 37.533187505 | 경도 : 127.131673932
서울특별시 양천구 오목로 193 (신정동)위도 : 37.525608522 | 경도 : 126.858862237
서울특별시 양천구 목동서로 387, 세림프라자 (신정동)위도 : None | 경도 : None
서울특별시 노원구 중계근린공원, 등나무근린공원위도 : None | 경도 : None
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 성동구 고산자로 164 (고산자로4길 일대)위도 : 37.555186726 | 경도 : 127.034798269
관악구 관악로 12길 29위도 : None | 경도 : None
서울특별시 양천구 목동동로 235, 목운초등학교.중학교 (목동)위도 : 37.527030486 | 경도 : 126.873023927
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 중구 동호로5길 16(신당동)위도 : 37.566385108 | 경도 : 127.001194093
서울특별시 종로구 자하문로16길 17-1(효자동)위도 : 37.581858245 | 경도 : 126.972960462
서울특별시 종로구 성균관로5길 일대위도 : 37.587140985 | 경도 : 126.993521939
서울특별시 강서구 양천로75길 57(염창동, 현대1차아파트)위도 : 37.552176623 | 경도 : 126.875668189
미아동 1353위도 : None | 경도 : None
오현로 208, 번동주공3단지위도 : 37.63013829 | 경도 : 127.041416174
서울특별시 강동구 상암로 251 (명일동, 고덕주공아파트)위도 : 37.546804141 | 경도 : 127.150632158
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 동작구 여의대방로20나길 39, 서울시립발달장애인복지관 (신대방동)위도 : 37.490490554 | 경도 : 126.918337968
서울특별시 서대문구 홍은중앙로 129, 홍은도담도서관 (홍은동)위도 : 37.601770912 | 경도 : 126.948927621
관내(인수봉로84길42 ~ 인수봉로 310 외 14개소)위도 : None | 경도 : None
서울특별시 종로구 효자로 39위도 : None | 경도 : None
서울특별시 중구 동호로 171(신당동)위도 : 37.553478373 | 경도 : 127.011305121
관악구 낙성대역 8길 일대위도 : 37.474465618 | 경도 : 126.963376154
서울특별시 금천구 가산디지털1로 205-28(가산동)위도 : None | 경도 : None
서울특별시 금천구 가산로3길 81(독산동)위도 : 37.472145244 | 경도 : 126.890924589
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 종로구 숭인동길 87, 돈암그리스도의교회 (숭인동)위도 : 37.578647297 | 경도 : 127.021124905
서울특별시 광진구 자양로 109 (자양동)위도 : 37.537435693 | 경도 : 127.083117976
서울특별시 광진구 자양로3가길 43 (자양동, 현대강변아파트)위도 : 37.528063504 | 경도 : 127.085603561
서울특별시 종로구 통의동 17위도 : 37.576524658 | 경도 : 126.973740737
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
화곡로 63가길 92위도 : 37.561523128 | 경도 : 126.849554516
한강대교 남단 노량진 방향(양녕로)위도 : None | 경도 : None
서울특별시 서초구 잠원로8길 25, 대림상가 (잠원동)위도 : None | 경도 : None
양천로 520위도 : 37.559569082 | 경도 : 126.857216629
서울특별시 종로구 자하문로24길 41-2 (효자동)위도 : 37.582301283 | 경도 : 126.972066011
서울특별시 영등포구 선유동1로 3 (양평동1가)위도 : 37.522496991 | 경도 : 126.891310444
서울특별시 영등포구 국제금융로7길 27 (여의도동, 삼부아파트)위도 : 37.523666045 | 경도 : 126.932621613
서울특별시 동작구 매봉로 99 (본동, 한신휴플러스아파트)위도 : 37.508827206 | 경도 : 126.951165202
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 노원구 상계동 산 24-1위도 : None | 경도 : None
서울특별시 광진구 구의동 562(올림픽대교 북단 일대)위도 : None | 경도 : None
서울특별시 성북구 동소문로26마길 41 외위도 : 37.595655032 | 경도 : 127.021266768
X위도 : 37.537798161 | 경도 : 127.211875874
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 성북구 솔샘로6길 63 (정릉동)위도 : 37.608823727 | 경도 : 127.008059086
서울특별시 성북구 오패산로 89, 여의도순복음성북교회 (하월곡동)위도 : 37.610095851 | 경도 : 127.035006371
서울특별시 성동구 난계로 114-31 (하왕십리동, 금호 베스트빌)위도 : 37.561980098 | 경도 : 127.025399871
서울특별시 중구 북창동 17-3 외 2필지위도 : None | 경도 : None
서울특별시 중구 을지로17길 13 (입정동)위도 : None | 경도 : None
서울특별시 중구 을지로15길 26 (입정동)위도 : 37.56765727 | 경도 : 126.993657048
서울특별시 도봉구 노해로63다길 21(창동)위도 : 37.653765027 | 경도 : 127.046154505
서울특별시 강남구 밤고개로15길 31(수서동)위도 : None | 경도 : None
서울특별시 강남구 선릉로 577, 조선내화빌딩 (역삼동)위도 : 37.509908873 | 경도 : 127.043649339
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 영등포구 신길로 156(신길동)위도 : 37.505903466 | 경도 : 126.911371954
X위도 : 37.537798161 | 경도 : 127.211875874
서울특별시 중구 충무로9길 17(을지로3가)위도 : 37.563739442 | 경도 : 127.001052801
서울특별시 중구 서애로1길 17 (묵정동)위도 : None | 경도 : None
서울특별시 강동구 상암로 331 (상일동, 상일우성타운)위도 : 37.545696514 | 경도 : 127.159431291
서울특별시 종로구 홍지문길 1 (홍지동)위도 : 37.599686533 | 경도 : 126.957138407
서울특별시 종로구 김상옥로 54 (효제동)위도 : 37.573276721 | 경도 : 127.003683681
X위도 : 37.537798161 | 경도 : 127.211875874
강북구 인수봉로 159, 한신대학교 신학대학원위도 : 37.634330836 | 경도 : 127.0117737
도봉구 관내위도 : None | 경도 : None
서울특별시 용산구 한강대로 26(한강로3가, 한강대우트럼프월드3차)위도 : 37.523147018 | 경도 : 126.962943324
서울특별시 성동구 마장동 339-2번지 일원위도 : None | 경도 : None
서울특별시 노원구 관내위도 : None | 경도 : None
서울특별시 금천구 독산로 163(시흥동)위도 : 37.461641238 | 경도 : 126.912719213
서울특별시 금천구 남부순환로 1366, 관악농협 (독산동)위도 : None | 경도 : None
서울특별시 동대문구 천호대로 64 (용두동)위도 : 37.573601128 | 경도 : 127.030297905
서울특별시 중랑구 망우로 218 (상봉동)위도 : 37.593912353 | 경도 : 127.07704186
서울특별시 강남구 도산대로 536, 프리마호텔 (청담동)위도 : 37.524303272 | 경도 : 127.052126409
서울특별시 노원구 공릉로46길 32 (공릉동, 삼익아파트)위도 : 37.626676513 | 경도 : 127.08200267
관악구 봉천동 915-25위도 : None | 경도 : None
서울특별시 서초구 서초동 1574-3위도 : None | 경도 : None
구일로4길65 외위도 : 37.494031795 | 경도 : 126.876660332

In [218]:
a,b = [],[]
for i,j in zip(latitude,fac['소재지도로명주소']):
    if i != None or j != 'X':
        a.append(i)
len(a)

1558

In [219]:
for i,j in zip(longitude,fac['소재지도로명주소']):
    if i != None or j != 'X':
        b.append(i)
len(b)

1558

In [220]:
fac['위도'] = latitude
fac['경도'] = longitude

In [221]:
fac

,Unnamed: 0,번호,사업자명(상호),공사장명,소재지도로명주소,소재지지번주소,관리기관명,데이터기준일자(신고일자),설치(공사)시작일,설치(공사)종료일,발생사업명,종료_year,종료_month,시작_year,시작_month,위도,경도
0,0,1,(주)계룡건설산업,경부선 원효가도교 개량공사,"서울특별시 용산구 한강대로77길 25, 남영역 (갈월동)",서울특별시 용산구 갈월동 96-1 남영역,서울특별시 용산구,2023-02-01,2023-03-31,2026-07-17,건설업,2026,7,2023,3,4.514710e+06,1.413438e+07
1,1,2,도시건축종합건설(주),재동 32-10 근린생활시설 신축공사,서울특별시 종로구 재동 32-10,서울특별시 종로구 재동 32-10,서울특별시 종로구,2023-05-16,2023-06-01,2024-07-31,건설업,2024,7,2023,6,NaN,NaN
2,2,3,(주)쿤스트종합건설,대치동 891-53 업무시설 및 근린생활시설 신축공사,X,서울특별시 강남구 대치동 891-53,서울특별시 강남구,2023-05-16,2021-07-26,2023-11-30,X,2023,11,2021,7,4.514336e+06,1.416116e+07
3,3,4,월드타워건설(주),대치동 921 근린생활시설 신축공사,X,서울특별시 강남구 대치동 921,서울특별시 강남구,2023-05-16,2023-05-20,2025-02-20,X,2025,2,2023,5,4.514336e+06,1.416116e+07
4,4,5,(주)수강건설,역삼동 643-1 근린생활시설 신축공사,X,서울특별시 강남구 역삼동 643-1,서울특별시 강남구,2023-05-16,2023-06-01,2025-05-31,X,2025,5,2023,6,4.514336e+06,1.416116e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1553,1585,1586,썸택건설(주),근린생활시설 신축,X,서울특별시 영등포구 양평동5가 67,서울특별시 영등포구,2023-12-06,2023-12-06,2025-02-28,건설업,2025,2,2023,12,4.514336e+06,1.416116e+07
1554,1588,1589,(주)에이텍건설,성수동2가 271-4 근린생활시설 신축공사,성수동2가 271-4,X,서울특별시 성동구,2023-12-28,2023-12-28,2023-12-28,X,2023,12,2023,12,NaN,NaN
1555,1591,1592,송도건설(주),조선왕릉 내 부적합시설물(개선관) 철거공사,서울특별시 노원구 공릉2동 산223-19 외 5필지,서울특별시 노원구 공릉2동 산223-19 외 5필지,서울특별시 노원구,2023-08-14,2023-08-14,2024-05-31,건설업,2024,5,2023,8,NaN,NaN
1556,1593,1594,(주)다영종합건설,서교동 372-9 복합건축물 신축공사,X,서교동 372-9,서울특별시 마포구,2023-03-02,2023-03-02,2024-10-30,건설업,2024,10,2023,3,4.514336e+06,1.416116e+07
1557,1594,1595,부운종합건설(주),서교동 380-39 맥클린사옥 신축공사,X,서교동 380-39,서울특별시 마포구,2023-02-06,2023-03-08,2024-07-15,X,2024,7,2023,3,4.514336e+06,1.416116e+07

In [222]:
fac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1558 entries, 0 to 1557
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     1558 non-null   int64
 1   번호             1558 non-null   int64
 2   사업자명(상호)       1558 non-null   object
 3   공사장명           1558 non-null   object
 4   소재지도로명주소       1558 non-null   object
 5   소재지지번주소        1558 non-null   object
 6   관리기관명          1558 non-null   object
 7   데이터기준일자(신고일자)  1558 non-null   object
 8   설치(공사)시작일      1558 non-null   object
 9   설치(공사)종료일      1558 non-null   object
 10  발생사업명          1558 non-null   object
 11  종료_year        1558 non-null   int64
 12  종료_month       1558 non-null   int64
 13  시작_year        1558 non-null   int64
 14  시작_month       1558 non-null   int64
 15  위도             1178 non-null   float64
 16  경도             1178 non-null   float64
dtypes: float64(2), int64(6), object(9)
memory usage: 207.0+ KB

In [223]:
fac.dropna().reset_index(drop =True).to_csv('factory23.csv', encoding='cp949', index = False)

In [228]:
d = pd.read_excel('제발.xlsx') ;d

,번호,사업자명(상호),공사장명,소재지도로명주소,Latitude,Longitude,소재지지번주소,Latitude.1,Longitude.1,관리기관명,데이터기준일자(신고일자),설치(공사)시작일,설치(공사)종료일,발생사업명,종료_year,종료_month,시작_year,시작_month
0,1,(주)계룡건설산업,경부선 원효가도교 개량공사,"서울특별시 용산구 한강대로77길 25, 남영역 (갈월동)",37.541624,126.971237,서울특별시 용산구 갈월동 96-1 남영역,37.541624,126.971237,서울특별시 용산구,2023-02-01,2023-03-31,2026-07-17,건설업,2026,7,2023,3
1,2,도시건축종합건설(주),재동 32-10 근린생활시설 신축공사,서울특별시 종로구 재동 32-10,37.579241,126.984249,서울특별시 종로구 재동 32-10,37.579241,126.984249,서울특별시 종로구,2023-05-16,2023-06-01,2024-07-31,건설업,2024,7,2023,6
2,3,(주)쿤스트종합건설,대치동 891-53 업무시설 및 근린생활시설 신축공사,X,NaN,NaN,서울특별시 강남구 대치동 891-53,37.504764,127.054794,서울특별시 강남구,2023-05-16,2021-07-26,2023-11-30,X,2023,11,2021,7
3,4,월드타워건설(주),대치동 921 근린생활시설 신축공사,X,NaN,NaN,서울특별시 강남구 대치동 921,37.499905,127.051537,서울특별시 강남구,2023-05-16,2023-05-20,2025-02-20,X,2025,2,2023,5
4,5,(주)수강건설,역삼동 643-1 근린생활시설 신축공사,X,NaN,NaN,서울특별시 강남구 역삼동 643-1,37.501928,127.034260,서울특별시 강남구,2023-05-16,2023-06-01,2025-05-31,X,2025,5,2023,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1553,1586,썸택건설(주),근린생활시설 신축,X,NaN,NaN,서울특별시 영등포구 양평동5가 67,37.538631,126.894251,서울특별시 영등포구,2023-12-06,2023-12-06,2025-02-28,건설업,2025,2,2023,12
1554,1589,(주)에이텍건설,성수동2가 271-4 근린생활시설 신축공사,성수동2가 271-4,37.541949,127.058400,X,NaN,NaN,서울특별시 성동구,2023-12-28,2023-12-28,2023-12-28,X,2023,12,2023,12
1555,1592,송도건설(주),조선왕릉 내 부적합시설물(개선관) 철거공사,서울특별시 노원구 공릉2동 산223-19 외 5필지,37.636216,127.097459,서울특별시 노원구 공릉2동 산223-19 외 5필지,37.636216,127.097459,서울특별시 노원구,2023-08-14,2023-08-14,2024-05-31,건설업,2024,5,2023,8
1556,1594,(주)다영종합건설,서교동 372-9 복합건축물 신축공사,X,NaN,NaN,서교동 372-9,37.552140,126.919435,서울특별시 마포구,2023-03-02,2023-03-02,2024-10-30,건설업,2024,10,2023,3
1557,1595,부운종합건설(주),서교동 380-39 맥클린사옥 신축공사,X,NaN,NaN,서교동 380-39,37.552550,126.915113,서울특별시 마포구,2023-02-06,2023-03-08,2024-07-15,X,2024,7,2023,3

In [229]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1558 entries, 0 to 1557
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   번호             1558 non-null   int64
 1   사업자명(상호)       1558 non-null   object
 2   공사장명           1558 non-null   object
 3   소재지도로명주소       1558 non-null   object
 4   Latitude       1077 non-null   float64
 5   Longitude      1077 non-null   float64
 6   소재지지번주소        1558 non-null   object
 7   Latitude.1     1479 non-null   float64
 8   Longitude.1    1479 non-null   float64
 9   관리기관명          1558 non-null   object
 10  데이터기준일자(신고일자)  1558 non-null   datetime64[ns]
 11  설치(공사)시작일      1558 non-null   datetime64[ns]
 12  설치(공사)종료일      1558 non-null   datetime64[ns]
 13  발생사업명          1558 non-null   object
 14  종료_year        1558 non-null   int64
 15  종료_month       1558 non-null   int64
 16  시작_year        1558 non-null   int64
 17  시작_month       1558 non-null   int64
dtypes: datetime64[ns](3), float64(4), int64(5), object(6)
memory usage: 219.2+ KB

In [232]:
d.dropna().reset_index(drop=True).to_csv('제발.csv', encoding = 'cp949', index =False)

In [235]:
d = d.dropna().reset_index(drop=True)

In [262]:
d.head(7)

,번호,사업자명(상호),공사장명,소재지도로명주소,Latitude,Longitude,소재지지번주소,Latitude.1,Longitude.1,관리기관명,데이터기준일자(신고일자),설치(공사)시작일,설치(공사)종료일,발생사업명,종료_year,종료_month,시작_year,시작_month,공사분류
0,1,(주)계룡건설산업,경부선 원효가도교 개량공사,"서울특별시 용산구 한강대로77길 25, 남영역 (갈월동)",37.541624,126.971237,서울특별시 용산구 갈월동 96-1 남영역,37.541624,126.971237,서울특별시 용산구,2023-02-01,2023-03-31,2026-07-17,건설업,2026,7,2023,3,경부선 원효가도교
1,2,도시건축종합건설(주),재동 32-10 근린생활시설 신축공사,서울특별시 종로구 재동 32-10,37.579241,126.984249,서울특별시 종로구 재동 32-10,37.579241,126.984249,서울특별시 종로구,2023-05-16,2023-06-01,2024-07-31,건설업,2024,7,2023,6,재동 32-10 근린생활시설
2,6,(주)서우건설산업,2023년 능동로 가로등 개량공사,서울특별시 광진구 중곡동 158-7~중곡동16,37.557647,127.080876,서울특별시 광진구 중곡동 158-7~중곡동16,37.557647,127.080876,서울특별시 광진구,2023-05-23,2023-05-25,2023-11-30,건설업,2023,11,2023,5,2023년 능동로 가로등
3,7,보형포장건설(주),수출의다리~독산역일대 노후도로 정비공사,서울특별시 금천구 벚꽃로 244(가산동),37.476690,126.885808,서울특별시 금천구 가산동 60-73 ~독산동 1001-14 도로,37.476690,126.885808,서울특별시 금천구,2023-02-21,2023-03-07,2023-06-07,건설업,2023,6,2023,3,수출의다리~독산역일대 노후도로
4,9,홍대 및 경의선숲길 주변 도로정비공사,홍대 및 경의선숲길 주변 도로정비공사,서울특별시 마포구 성미산로 112 (연남동),37.562062,126.919576,서울특별시 마포구 연남동 504-1,37.562062,126.919576,서울특별시 마포구,2023-05-23,2023-05-23,2023-05-23,X,2023,5,2023,5,홍대 및 경의선숲길 주변 도로
5,11,(주)부영씨엔씨,숲속마을 신동아파밀리에 아파트 외벽 균열보수 및 재도장 공사,"서울특별시 동작구 여의대방로10길 100 (신대방동, 숲속마을 신동아 파밀리에)",37.491746,126.914539,서울특별시 동작구 신대방동 717 숲속마을 신동아 파밀리에,37.491746,126.914539,서울특별시 동작구,2023-04-28,2023-05-08,2023-06-30,건설업,2023,6,2023,5,숲속마을 신동아파밀리에 아파트 외벽 균열보수 및 재도
6,12,(주)대평건설,2023 시도상 보도블럭 정비공사(연간단가),"서울특별시 종로구 평창문화로 130, 귀빈빌딩 (평창동)",37.609012,126.974532,서울특별시 종로구 평창동 66-32 귀빈빌딩,37.609012,126.974532,서울특별시 종로구,2023-04-28,2023-05-03,2023-09-30,건설업,2023,9,2023,5,2023 시도상 보도블럭 정비공사(연

공사명에 따른 가중치를 다르게 하기 위한 과정

In [283]:
import re
answer = []
p = re.compile(".+공사")
for i in d['공사장명']:
    temp = p.findall(i)
    try:
        lst = temp[0].split()
        answer.append(lst[-1])
    except IndexError:
        answer.append('건축공사')
set(answer)

{'IC보수공사',
 '가로주택사업신축공사',
 '개량공사',
 '개발공사',
 '개보수공사',
 '개선공사',
 '개설공사',
 '건립공사',
 '건설공사',
 '건설공사(공사',
 '건축공사',
 '건축물해체공사',
 '공사',
 '공원공사',
 '공원조성공사',
 '관로공사',
 '교량개량공사',
 '교체공사',
 '구축공사',
 '기능개선(유형변경)공사',
 '기반시설공사',
 '기타공사',
 '긴급공사',
 '내진보강공사',
 '단면확장공사',
 '대수선공사',
 '도로개설공사',
 '도로굴착복구공사',
 '도로정비공사',
 '도시형생활주택(소형주택)신축공사',
 '도장공사',
 '뒷골목도로정비공사',
 '등)정비공사',
 '리뉴얼공사',
 '리모델링공사',
 '매립공사',
 '매설공사',
 '반출정화공사',
 '방수공사',
 '보강공사',
 '보도교체공사',
 '보수공사',
 '보행환경개선공사',
 '보행환경공사',
 '복구공사',
 '복원공사',
 '복합건축물신축공사',
 '복합방수공사',
 '부대공사',
 '부설공사',
 '부지조성공사',
 '빗물유입시설확충공사',
 '사전공사',
 '생활주택(다세대)신축공사',
 '서초네이처힐1단지10년차하자보수종결공사',
 '설치공사',
 '성능개선공사',
 '수선공사',
 '슁글보수공사',
 '시설공사',
 '신관증축공사',
 '신설공사',
 '신축공사',
 '압력보정공사',
 '오피스텔신축공사',
 '옥상방수공사',
 '외부공사',
 '외부도장공사',
 '외부환경(포장)개선공사',
 '외부환경개선공사',
 '용도변경공사',
 '유지관리공사',
 '유지보수공사',
 '이설공사',
 '잔재처리공사',
 '재건축공사',
 '재도장공사',
 '재생공사',
 '재편공사',
 '전력구공사',
 '전력인입공사',
 '정비공사',
 '정비기반시설(공원)공사',
 '정비기반시설공사',
 '정화공사',
 '조경공사',
 '조경리뉴얼공사',
 '조성공사',
 '종합정비공사',
 '주예비공사',
 '준설공사',
 '증개축공사',
 '증축공사',
 '지중화공사',
 '처리공사',
 '철거공사',
 '추가공사',
 '축조공사',
 '충진공사',
 '토공사',
 '토목건축공사',
 '토목공사',
 '토양정화공사',
 '통신관로공사',
 '폐기물처리공사',
 '포장개선공사',
 '포장공사',
 '포장보수공사',
 '하수관로개량공사',
 '한강더퍼스트타워청년주택신축공사',
 '한강트럼프월드3차아파트도장공사',
 '해체공사',
 '화장공사',
 '확장공사',
 '환경개선공사'}

In [288]:
result = []
for i in answer:
    if i in ('건설공사(공사','가로주택사업신축공사', '도시형생활주택(소형주택)신축공사', '복합건축물신축공사',
     '생활주택(다세대)신축공사','신축공사','오피스텔신축공사', '재건축공사','한강더퍼스트타워청년주택신축공사','건립공사',
     '건설공사','서초네이처힐1단지10년차하자보수종결공사','신설공사','철거공사','한강트럼프월드3차아파트도장공사',
     ):
        result.append('건축공사')


    elif i in ('IC보수공사','개보수공사','빗물유입시설확충공사', '서초네이처힐1단지10년차하자보수종결공사', '슁글보수공사',
     '옥상방수공사','유지보수공사','내진보강공사', '대수선공사','도로굴착복구공사','도장공사','뒷골목도로정비공사',
     '등)정비공사','방수공사','보강공사','복구공사','복원공사','복합방수공사','수선공사','포장보수공사',):
        result.append('보수공사')
    
    
    elif i in ('개량공사','개설공사','교량개량공사','구축공사','기반시설공사','도로개설공사', '부대공사','준설공사','증개축공사',
    '증축공사','축조공사','토공사','토목건축공사','토목공사','포장개선공사','포장공사','확장공사',
 ):
        result.append('토목공사')


    elif i in ('공원공사','공원조성공사','정비기반시설(공원)공사','조경공사','조경리뉴얼공사','부지조성공사','정비기반시설(공원)공사',
    '정화공사','조경공사','조경리뉴얼공사','조성공사','토양정화공사','환경개선공사'):
        result.append('환경공사')
    
    
    elif i in ('뒷골목도로정비공사','등)정비공사','긴급공사','리모델링공사','매립공사','반출정화공사','보도교체공사',
    '보행환경개선공사','보행환경공사','빗물유입시설확충공사','압력보정공사', '용도변경공사','전력구공사','전력인입공사','주예비공사',
     '지중화공사','통신관로공사', '폐기물처리공사','해체공사','화장공사',
    ):
        result.append('특수공사')
    
    
    elif i in ('개선공사','교체공사','기능개선(유형변경)공사','단면확장공사','도로정비공사','리뉴얼공사','설치공사',
    '성능개선공사','신관증축공사','외부환경(포장)개선공사','외부환경개선공사','하수관로개량공사',):
        result.append('개발공사')
    
    
    else:
        result.append('기타공사')

In [289]:
for i in set(result):
    print(i)

토목공사
건축공사
보수공사
특수공사
개발공사
환경공사
기타공사

In [290]:
d['공사분류'] = result ;d.head(4)

,번호,사업자명(상호),공사장명,소재지도로명주소,Latitude,Longitude,소재지지번주소,Latitude.1,Longitude.1,관리기관명,데이터기준일자(신고일자),설치(공사)시작일,설치(공사)종료일,발생사업명,종료_year,종료_month,시작_year,시작_month,공사분류
0,1,(주)계룡건설산업,경부선 원효가도교 개량공사,"서울특별시 용산구 한강대로77길 25, 남영역 (갈월동)",37.541624,126.971237,서울특별시 용산구 갈월동 96-1 남영역,37.541624,126.971237,서울특별시 용산구,2023-02-01,2023-03-31,2026-07-17,건설업,2026,7,2023,3,토목공사
1,2,도시건축종합건설(주),재동 32-10 근린생활시설 신축공사,서울특별시 종로구 재동 32-10,37.579241,126.984249,서울특별시 종로구 재동 32-10,37.579241,126.984249,서울특별시 종로구,2023-05-16,2023-06-01,2024-07-31,건설업,2024,7,2023,6,건축공사
2,6,(주)서우건설산업,2023년 능동로 가로등 개량공사,서울특별시 광진구 중곡동 158-7~중곡동16,37.557647,127.080876,서울특별시 광진구 중곡동 158-7~중곡동16,37.557647,127.080876,서울특별시 광진구,2023-05-23,2023-05-25,2023-11-30,건설업,2023,11,2023,5,토목공사
3,7,보형포장건설(주),수출의다리~독산역일대 노후도로 정비공사,서울특별시 금천구 벚꽃로 244(가산동),37.476690,126.885808,서울특별시 금천구 가산동 60-73 ~독산동 1001-14 도로,37.476690,126.885808,서울특별시 금천구,2023-02-21,2023-03-07,2023-06-07,건설업,2023,6,2023,3,기타공사

In [292]:
d['공사분류_인코딩'] =  d['공사분류'].replace({'토목공사':4,'건축공사':3,'보수공사':2,'특수공사':3, '개발공사':4,'환경공사':1,'기타공사':2})

In [300]:
start, during = [],[]
for (y1,m1,y2,m2) in zip(d['시작_year'], d['시작_month'],d['종료_year'],d['종료_month']):
    start.append(((2024-y1)*365-m1*30.5)/30)
    if y2 == 2023:
        during.append(m2)
    else:
        during.append(12)
print(start)
print(during)

[9.116666666666667, 6.066666666666666, 7.083333333333333, 9.116666666666667, 7.083333333333333, 7.083333333333333, 7.083333333333333, 6.066666666666666, 6.066666666666666, 6.066666666666666, 6.066666666666666, 7.083333333333333, 7.083333333333333, 11.15, 7.083333333333333, 7.083333333333333, 9.116666666666667, 8.1, 9.116666666666667, 7.083333333333333, 10.133333333333333, 10.133333333333333, 10.133333333333333, 8.1, 8.1, 9.116666666666667, 8.1, 8.1, 8.1, 8.1, 8.1, 8.1, 6.066666666666666, 6.066666666666666, 8.1, 6.066666666666666, 6.066666666666666, 6.066666666666666, 29.383333333333333, 6.066666666666666, 8.1, 6.066666666666666, 7.083333333333333, 9.116666666666667, 7.083333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 6.066666666666666, 7.083333333333333, 26.333333333333332, 7.083333333333333, 8.1, 8.1, 8.1, 10.133333333333333, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 17.216666666666665, 11.15, 10.133333333333333, 7.083333333333333, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 10.133333333333333, 9.116666666666667, 10.133333333333333, 9.116666666666667, 9.116666666666667, 8.1, 7.083333333333333, 7.083333333333333, 7.083333333333333, 9.116666666666667, 11.15, 9.116666666666667, 9.116666666666667, 18.233333333333334, 9.116666666666667, 9.116666666666667, 8.1, 8.1, 10.133333333333333, 11.15, 11.15, 10.133333333333333, 8.1, 10.133333333333333, 8.1, 7.083333333333333, 7.083333333333333, 8.1, 10.133333333333333, 10.133333333333333, 13.15, 9.116666666666667, 7.083333333333333, 10.133333333333333, 9.116666666666667, 7.083333333333333, 7.083333333333333, 7.083333333333333, 11.15, 8.1, 8.1, 9.116666666666667, 12.133333333333333, 8.1, 10.133333333333333, 9.116666666666667, 10.133333333333333, 9.116666666666667, 10.133333333333333, 9.116666666666667, 9.116666666666667, 9.116666666666667, 10.133333333333333, 9.116666666666667, 8.1, 7.083333333333333, 7.083333333333333, 7.083333333333333, 10.133333333333333, 9.116666666666667, 9.116666666666667, 7.083333333333333, 9.116666666666667, 6.066666666666666, 8.1, 9.116666666666667, 9.116666666666667, 8.1, 8.1, 7.083333333333333, 6.066666666666666, 9.116666666666667, 9.116666666666667, 10.133333333333333, 10.133333333333333, 8.1, 7.083333333333333, 7.083333333333333, 6.066666666666666, 8.1, 9.116666666666667, 7.083333333333333, 8.1, 8.1, 7.083333333333333, 7.083333333333333, 10.133333333333333, 18.233333333333334, 6.066666666666666, 9.116666666666667, 9.116666666666667, 8.1, 9.116666666666667, 9.116666666666667, 9.116666666666667, 11.15, 11.15, 11.15, 11.15, 11.15, 10.133333333333333, 8.1, 8.1, 8.1, 7.083333333333333, 7.083333333333333, 9.116666666666667, 7.083333333333333, 7.083333333333333, 11.15, 9.116666666666667, 9.116666666666667, 7.083333333333333, 8.1, 8.1, 11.15, 7.083333333333333, 8.1, 8.1, 8.1, 6.066666666666666, 11.15, 11.15, 8.1, 8.1, 8.1, 8.1, 9.116666666666667, 9.116666666666667, 9.116666666666667, 8.1, 8.1, 8.1, 10.133333333333333, 6.066666666666666, 6.066666666666666, 10.133333333333333, 25.316666666666666, 9.116666666666667, 8.1, 9.116666666666667, 6.066666666666666, 6.066666666666666, 6.066666666666666, 7.083333333333333, 10.133333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 8.1, 8.1, 7.083333333333333, 7.083333333333333, 5.05, 6.066666666666666, 6.066666666666666, 7.083333333333333, 7.083333333333333, 8.1, 8.1, 9.116666666666667, 7.083333333333333, 12.133333333333333, 29.383333333333333, 6.066666666666666, 8.1, 8.1, 9.116666666666667, 9.116666666666667, 8.1, 9.116666666666667, 10.133333333333333, 10.133333333333333, 8.1, 8.1, 8.1, 8.1, 8.1, 7.083333333333333, 7.083333333333333, 8.1, 8.1, 8.1, 8.1, 9.116666666666667, 7.083333333333333, 7.083333333333333, 7.083333333333333, 10.133333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 6.066666666666666, 10.133333333333333, 9.116666666666667, 7.083333333333333, 6.066666666666666, 8.1, 6.066666666666666, 7.083333333333333, 8.1, 8.1, 8.1, 31.416666666666668, 4.033333333333333, 9.116666666666667, 7.083333333333333, 9.116666666666667, 9.116666666666667, 7.083333333333333, 9.116666666666667, 6.066666666666666, 11.15, 11.15, 11.15, 6.066666666666666, 7.083333333333333, 7.083333333333333, 8.1, 8.1, 8.1, 8.1, 6.066666666666666, 5.05, 7.083333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 5.05, 8.1, 7.083333333333333, 8.1, 7.083333333333333, 7.083333333333333, 9.116666666666667, 9.116666666666667, 7.083333333333333, 9.116666666666667, 7.083333333333333, 7.083333333333333, 6.066666666666666, 10.133333333333333, 8.1, 8.1, 8.1, 8.1, 7.083333333333333, 7.083333333333333, 6.066666666666666, 8.1, 8.1, 8.1, 6.066666666666666, 10.133333333333333, 10.133333333333333, 10.133333333333333, 10.133333333333333, 9.116666666666667, 10.133333333333333, 10.133333333333333, 8.1, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 10.133333333333333, 10.133333333333333, 10.133333333333333, 9.116666666666667, 9.116666666666667, 8.1, 20.266666666666666, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 8.1, 8.1, 8.1, 8.1, 7.083333333333333, 9.116666666666667, 8.1, 8.1, 8.1, 8.1, 9.116666666666667, 10.133333333333333, 10.133333333333333, 9.116666666666667, 6.066666666666666, 9.116666666666667, 6.066666666666666, 9.116666666666667, 9.116666666666667, 6.066666666666666, 7.083333333333333, 7.083333333333333, 8.1, 9.116666666666667, 6.066666666666666, 7.083333333333333, 9.116666666666667, 8.1, 8.1, 8.1, 8.1, 11.15, 9.116666666666667, 9.116666666666667, 9.116666666666667, 8.1, 8.1, 8.1, 8.1, 8.1, 8.1, 8.1, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 8.1, 8.1, 8.1, 8.1, 9.116666666666667, 9.116666666666667, 9.116666666666667, 7.083333333333333, 7.083333333333333, 7.083333333333333, 8.1, 7.083333333333333, 7.083333333333333, 6.066666666666666, 11.15, 9.116666666666667, 7.083333333333333, 9.116666666666667, 9.116666666666667, 8.1, 8.1, 8.1, 8.1, 7.083333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 6.066666666666666, 8.1, 11.15, 7.083333333333333, 7.083333333333333, 7.083333333333333, 10.133333333333333, 10.133333333333333, 7.083333333333333, 10.133333333333333, 7.083333333333333, 7.083333333333333, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 9.116666666666667, 8.1, 9.116666666666667, 9.116666666666667, 9.116666666666667, 8.1, 8.1, 8.1, 11.15, 8.1, 11.15, 10.133333333333333, 12.133333333333333, 11.15, 10.133333333333333, 9.116666666666667, 7.083333333333333, 8.1, 7.083333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 11.15, 10.133333333333333, 7.083333333333333, 8.1, 11.15, 9.116666666666667, 9.116666666666667, 9.116666666666667, 7.083333333333333, 8.1, 10.133333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 10.133333333333333, 10.133333333333333, 10.133333333333333, 8.1, 8.1, 8.1, 9.116666666666667, 7.083333333333333, 7.083333333333333, 15.183333333333334, 8.1, 8.1, 8.1, 8.1, 7.083333333333333, 7.083333333333333, 7.083333333333333, 7.083333333333333, 6.066666666666666, 6.066666666666666, 9.116666666666667, 6.066666666666666, 6.066666666666666, 9.116666666666667, 10.133333333333333, 9.116666666666667, 9.116666666666667, 9.116666666666667, 10.133333333333333, 11.15, 11.15, 10.133333333333333, 10.133333333333333, 10.133333333333333, 10.133333333333333, 8.1, 8.1, 10.133333333333333, 9.116666666666667, 6.066666666666666, 6.066666666666666, 8.1, 8.1, 10.133333333333333, 8.1, 11.15, 8.1, 9.116666666666667, 9.116666666666667, 7.083333333333333, 7.083333333333333, 9.116666666666667, 9.116666666666667, 10.133333333333333, 9.116666666666667, 10.133333333333333, 8.1, 10.133333333333333, 7.083333333333333, 7.083333333333333, 9.116666666666667, 9.116666666666667, 8.1, 7.083333333333333, 8.1, 9.116666666666667, 9.116666666666667, 7.083333333333333, 7.083333333333333, 6.066666666666666, 7.083333333333333, 8.1, 9.116666666666667, 6.066666666666666, 8.1, 2.0, 0.9833333333333333, 2.0, 3.0166666666666666, 2.0, 2.0, 6.066666666666666, 6.066666666666666, 6.066666666666666, 4.033333333333333, 3.0166666666666666, 6.066666666666666, 2.0, 0.9833333333333333, 2.0, 6.066666666666666, 3.0166666666666666, 5.05, 5.05, -0.03333333333333333, -0.03333333333333333, 6.066666666666666, 3.0166666666666666, 6.066666666666666, 2.0, 6.066666666666666, 6.066666666666666, 6.066666666666666, 3.0166666666666666, 6.066666666666666, 6.066666666666666, 6.066666666666666, 6.066666666666666, 5.05, 6.066666666666666, 2.0, 2.0, 5.05, -0.03333333333333333, 0.9833333333333333, 0.9833333333333333, 2.0, 2.0, 5.05, 5.05, 3.0166666666666666, 2.0, 5.05, 5.05, 3.0166666666666666, 3.0166666666666666, 3.0166666666666666, 3.0166666666666666, 0.9833333333333333, 0.9833333333333333, 2.0, 2.0, 5.05, 3.0166666666666666, 3.0166666666666666, -0.03333333333333333, -0.03333333333333333, 5.05, 5.05, 3.0166666666666666, 0.9833333333333333, 4.033333333333333, 2.0, 5.05, 24.3, 5.05, 3.0166666666666666, 2.0, -0.03333333333333333, 5.05, 5.05, 5.05, 0.9833333333333333, 4.033333333333333, 11.15, 5.05, 5.05, 4.033333333333333, 4.033333333333333, 3.0166666666666666, 4.033333333333333, 5.05, 0.9833333333333333, 6.066666666666666, 2.0, 4.033333333333333, 0.9833333333333333, -0.03333333333333333, -0.03333333333333333, 4.033333333333333, 4.033333333333333, 0.9833333333333333, 2.0, 2.0, 2.0, 4.033333333333333, 3.0166666666666666, 2.0, 4.033333333333333, 6.066666666666666, 3.0166666666666666, 3.0166666666666666, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 4.033333333333333, 4.033333333333333, 3.0166666666666666, 3.0166666666666666, 0.9833333333333333, 3.0166666666666666, 2.0, 2.0, 2.0, -0.03333333333333333, 4.033333333333333, 0.9833333333333333, 4.033333333333333, 3.0166666666666666, 2.0, 0.9833333333333333, -0.03333333333333333, 0.9833333333333333, 5.05, 6.066666666666666, 2.0, 2.0, 3.0166666666666666, 6.066666666666666, 6.066666666666666, 6.066666666666666, 6.066666666666666, 3.0166666666666666, 0.9833333333333333, 6.066666666666666, 6.066666666666666, 5.05, 6.066666666666666, 2.0, 2.0, 2.0, 6.066666666666666, 6.066666666666666, -0.03333333333333333, 5.05, 6.066666666666666, 0.9833333333333333, 2.0, 0.9833333333333333, 2.0, 3.0166666666666666, 5.05, 6.066666666666666, 3.0166666666666666, 6.066666666666666, 5.05, 5.05, 3.0166666666666666, 0.9833333333333333, 5.05, 0.9833333333333333, 3.0166666666666666, 5.05, 3.0166666666666666, 5.05, 2.0, 0.9833333333333333, -0.03333333333333333, 4.033333333333333, -0.03333333333333333, 0.9833333333333333, 0.9833333333333333, 2.0, 2.0, -0.03333333333333333, -0.03333333333333333, 4.033333333333333, 2.0, 2.0, -0.03333333333333333, -0.03333333333333333, -0.03333333333333333, 5.05, 4.033333333333333, 2.0, 4.033333333333333, 4.033333333333333, 5.05, 0.9833333333333333, 4.033333333333333, 5.05, 0.9833333333333333, 0.9833333333333333, 5.05, 0.9833333333333333, 4.033333333333333, 5.05, 5.05, 3.0166666666666666, 4.033333333333333, 4.033333333333333, 4.033333333333333, -0.03333333333333333, -0.03333333333333333, -0.03333333333333333, 2.0, 3.0166666666666666, -0.03333333333333333, -0.03333333333333333, 3.0166666666666666, 5.05, -0.03333333333333333, -0.03333333333333333, 3.0166666666666666, 4.033333333333333, 4.033333333333333, 4.033333333333333, 4.033333333333333, 3.0166666666666666, 4.033333333333333, 4.033333333333333, 3.0166666666666666, 4.033333333333333, 2.0, -0.03333333333333333, -0.03333333333333333, 8.1, 2.0, 2.0, 4.033333333333333, 4.033333333333333, 3.0166666666666666, 3.0166666666666666, 3.0166666666666666, -0.03333333333333333, 4.033333333333333, -0.03333333333333333, 3.0166666666666666, 3.0166666666666666, 3.0166666666666666, 0.9833333333333333, 3.0166666666666666, 0.9833333333333333, 2.0, -0.03333333333333333, -0.03333333333333333, -0.03333333333333333, 3.0166666666666666, 6.066666666666666, 3.0166666666666666, 3.0166666666666666, -0.03333333333333333, -0.03333333333333333, 4.033333333333333, 3.0166666666666666, 3.0166666666666666, 2.0, 7.083333333333333, -0.03333333333333333, 6.066666666666666, 3.0166666666666666, 6.066666666666666, 5.05, 7.083333333333333, 6.066666666666666, 6.066666666666666, -0.03333333333333333, 6.066666666666666, 6.066666666666666, 2.0, 2.0, 6.066666666666666, 6.066666666666666, 3.0166666666666666, -0.03333333333333333, -0.03333333333333333, 6.066666666666666, 6.066666666666666, 3.0166666666666666, 2.0, 2.0, 6.066666666666666, 2.0, 6.066666666666666, 6.066666666666666, 3.0166666666666666, 5.05, 3.0166666666666666, 3.0166666666666666, 5.05, 3.0166666666666666, 0.9833333333333333, 2.0, 2.0, 6.066666666666666, 6.066666666666666, 5.05, 2.0, 2.0, 2.0, 3.0166666666666666, 3.0166666666666666, 3.0166666666666666, 5.05, 5.05, 2.0, 0.9833333333333333, 0.9833333333333333, 6.066666666666666, 2.0, 2.0, 2.0, 6.066666666666666, 2.0, 2.0, 5.05, 4.033333333333333, 4.033333333333333, 2.0, 5.05, 0.9833333333333333, 0.9833333333333333, 5.05, 2.0, 2.0, 0.9833333333333333, -0.03333333333333333, 5.05, 5.05, 0.9833333333333333, 4.033333333333333, 4.033333333333333, 5.05, 2.0, 5.05, 4.033333333333333, 20.266666666666666, 5.05, 4.033333333333333, 5.05, 4.033333333333333, 4.033333333333333, 0.9833333333333333, 2.0, 5.05, 5.05, 4.033333333333333, 5.05, 2.0, -0.03333333333333333, 4.033333333333333, 3.0166666666666666, 4.033333333333333, 4.033333333333333, 4.033333333333333, 4.033333333333333, 4.033333333333333, 4.033333333333333, 0.9833333333333333, 0.9833333333333333, 4.033333333333333, 2.0, 3.0166666666666666, 4.033333333333333, 3.0166666666666666, 14.166666666666666, 2.0, 2.0, 6.066666666666666, 5.05, 3.0166666666666666, 3.0166666666666666, 5.05, 6.066666666666666, 4.033333333333333, 2.0, 6.066666666666666, 5.05, 3.0166666666666666, 23.316666666666666, 2.0, 3.0166666666666666, 2.0, 3.0166666666666666, 5.05, 5.05, 5.05, 4.033333333333333, 2.0, 2.0, 5.05, 6.066666666666666, 2.0, 3.0166666666666666, 6.066666666666666, 5.05, 3.0166666666666666, 2.0, 2.0, 6.066666666666666, 6.066666666666666, 8.1, 3.0166666666666666, 0.9833333333333333, 0.9833333333333333, 2.0, 5.05, 5.05, 5.05, 5.05, 4.033333333333333, 2.0, 0.9833333333333333, 3.0166666666666666, 3.0166666666666666, 5.05, 3.0166666666666666, 6.066666666666666, -0.03333333333333333, -0.03333333333333333, 3.0166666666666666, 4.033333333333333, 4.033333333333333, 3.0166666666666666, 3.0166666666666666, 2.0, 2.0, 2.0, 23.316666666666666, 3.0166666666666666, 3.0166666666666666, 0.9833333333333333, 0.9833333333333333, -0.03333333333333333, -0.03333333333333333, 6.066666666666666, 3.0166666666666666, -0.03333333333333333, 3.0166666666666666, 3.0166666666666666, -0.03333333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 4.033333333333333]
[12, 12, 11, 6, 5, 6, 9, 11, 12, 11, 12, 9, 6, 12, 10, 5, 4, 12, 8, 10, 10, 12, 4, 11, 11, 12, 5, 4, 9, 5, 12, 7, 7, 12, 10, 6, 6, 6, 11, 6, 7, 6, 10, 4, 5, 8, 12, 8, 12, 12, 12, 5, 9, 8, 9, 5, 2, 5, 9, 6, 6, 12, 12, 12, 3, 4, 12, 7, 3, 8, 5, 2, 12, 12, 6, 12, 11, 11, 8, 12, 5, 2, 12, 12, 2, 3, 3, 12, 12, 12, 7, 7, 12, 10, 12, 6, 8, 7, 4, 11, 5, 11, 8, 6, 2, 3, 10, 6, 6, 12, 4, 12, 12, 5, 12, 12, 3, 5, 12, 6, 12, 12, 12, 7, 12, 12, 12, 12, 12, 12, 12, 9, 5, 4, 12, 12, 3, 3, 9, 9, 6, 12, 12, 5, 5, 12, 12, 7, 12, 7, 12, 12, 11, 4, 10, 12, 12, 12, 7, 11, 4, 12, 9, 6, 12, 12, 9, 12, 12, 6, 10, 8, 5, 8, 6, 12, 7, 12, 12, 7, 5, 3, 12, 6, 5, 6, 4, 12, 12, 11, 5, 12, 12, 12, 8, 4, 10, 8, 12, 8, 3, 9, 4, 11, 12, 12, 6, 12, 4, 3, 12, 7, 12, 7, 6, 12, 7, 10, 5, 5, 7, 7, 12, 11, 10, 12, 6, 12, 12, 12, 12, 12, 7, 12, 9, 11, 7, 10, 6, 7, 5, 12, 12, 12, 12, 12, 12, 12, 9, 4, 12, 7, 11, 12, 7, 4, 9, 5, 12, 9, 2, 9, 12, 12, 12, 4, 11, 11, 12, 12, 6, 12, 8, 4, 4, 6, 12, 12, 5, 8, 4, 6, 3, 12, 1, 3, 5, 11, 6, 12, 6, 6, 12, 5, 12, 12, 12, 9, 6, 12, 12, 10, 12, 9, 12, 12, 7, 12, 5, 9, 12, 8, 6, 8, 5, 6, 9, 12, 9, 6, 12, 8, 10, 9, 11, 12, 12, 12, 12, 12, 12, 12, 7, 4, 12, 12, 4, 12, 12, 10, 4, 12, 12, 12, 12, 12, 12, 5, 12, 5, 6, 4, 3, 12, 12, 5, 4, 6, 6, 12, 10, 12, 12, 4, 12, 3, 10, 6, 12, 12, 12, 12, 4, 12, 10, 12, 11, 6, 3, 7, 5, 5, 12, 6, 6, 12, 6, 12, 6, 6, 10, 10, 10, 6, 12, 12, 9, 3, 12, 12, 6, 12, 6, 5, 5, 6, 12, 12, 12, 5, 5, 6, 9, 11, 8, 12, 12, 12, 12, 12, 7, 11, 10, 6, 5, 7, 5, 11, 12, 10, 12, 11, 11, 11, 8, 8, 6, 7, 5, 6, 12, 12, 4, 12, 12, 12, 3, 5, 12, 6, 4, 4, 1, 6, 2, 12, 12, 1, 8, 6, 12, 9, 12, 11, 6, 11, 12, 4, 6, 5, 4, 12, 12, 12, 12, 12, 9, 6, 12, 12, 8, 7, 5, 5, 5, 5, 10, 12, 12, 10, 6, 5, 4, 9, 10, 12, 12, 12, 6, 10, 7, 12, 9, 7, 9, 4, 12, 3, 12, 12, 6, 1, 7, 12, 12, 12, 12, 12, 12, 12, 12, 12, 6, 12, 12, 12, 4, 12, 5, 12, 12, 8, 12, 4, 3, 11, 12, 4, 12, 12, 7, 12, 7, 12, 6, 12, 12, 8, 11, 12, 12, 12, 12, 8, 6, 4, 11, 11, 10, 12, 11, 12, 6, 6, 6, 12, 9, 12, 12, 12, 12, 6, 12, 12, 7, 12, 12, 12, 12, 7, 11, 12, 6, 6, 11, 7, 10, 12, 12, 12, 9, 12, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 7, 12, 12, 10, 11, 12, 12, 12, 10, 10, 12, 12, 12, 12, 12, 10, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 11, 12, 12, 11, 12, 12, 12, 7, 8, 12, 12, 12, 10, 12, 12, 12, 12, 12, 12, 12, 8, 8, 11, 12, 11, 10, 12, 12, 12, 12, 12, 12, 12, 11, 11, 11, 12, 12, 9, 9, 12, 12, 11, 10, 11, 12, 10, 11, 12, 10, 12, 12, 12, 11, 10, 12, 10, 12, 10, 12, 12, 10, 10, 12, 12, 6, 6, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 12, 12, 12, 12, 12, 12, 11, 12, 12, 12, 7, 12, 12, 12, 12, 11, 12, 12, 12, 12, 12, 12, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 9, 12, 10, 9, 12, 11, 11, 12, 10, 12, 12, 11, 12, 12, 7, 12, 12, 8, 12, 12, 12, 12, 12, 12, 12, 12, 12, 10, 9, 12, 12, 12, 9, 12, 12, 9, 12, 11, 12, 12, 9, 12, 12, 12, 12, 12, 11, 11, 10, 11, 11, 9, 12, 12, 12, 12, 10, 11, 12, 12, 12, 12, 12, 12, 12, 12, 6, 12, 10, 12, 12, 12, 11, 11, 12, 11, 12, 12, 9, 6, 8, 12, 6, 10, 12, 9, 11, 12, 12, 9, 12, 12, 12, 12, 8, 12, 12, 12, 12, 11, 11, 7, 12, 10, 12, 11, 9, 12, 12, 12, 12, 12, 9, 7, 12, 11, 12, 12, 12, 9, 11, 12, 9, 12, 12, 12, 9, 12, 11, 12, 8, 11, 10, 10, 12, 12, 12, 8, 11, 12, 7, 12, 10, 12, 12, 12, 12, 12, 12, 9, 9, 12, 7, 12, 9, 7, 12, 8, 12, 11, 12, 12, 8, 8, 12, 11, 12, 12, 9, 12, 10, 12, 8, 8, 8, 8, 12, 12, 10, 10, 12, 11, 11, 7, 10, 12, 12, 12, 12, 12, 12, 12, 10, 12, 11, 10, 12, 12, 12, 12, 12, 12, 10, 11, 12, 8, 12, 12, 9, 12, 10, 12, 12, 12, 12, 12, 11, 7, 12, 7, 9, 12, 12, 12, 12, 10, 10, 10, 12, 10, 12, 12, 10, 12, 12, 8, 12, 12, 11, 9, 12, 9, 9, 12, 12, 12, 12, 12, 12, 11, 12, 12, 12, 11, 12, 12, 12, 10, 12, 11, 12, 11, 12]

해당 기간 동안에 얼마나 많은 기간을 걸쳤는지 확인하기 위한 과정

In [301]:
d['운영기간'] = start
d['지속기간'] = during

In [305]:
result = []
for (year,month,encoding) in zip(d['운영기간'],d['지속기간'],d['공사분류_인코딩']):
    result.append(year*(month/12)*encoding)
d['공사장_지수'] = result
d['공사장_지수'] = d['공사장_지수'].apply(lambda x: abs(x) if x<0 else x);d

,번호,사업자명(상호),공사장명,소재지도로명주소,Latitude,Longitude,소재지지번주소,Latitude.1,Longitude.1,관리기관명,...,발생사업명,종료_year,종료_month,시작_year,시작_month,공사분류,공사분류_인코딩,운영기간,지속기간,공사장_지수
0,1,(주)계룡건설산업,경부선 원효가도교 개량공사,"서울특별시 용산구 한강대로77길 25, 남영역 (갈월동)",37.541624,126.971237,서울특별시 용산구 갈월동 96-1 남영역,37.541624,126.971237,서울특별시 용산구,...,건설업,2026,7,2023,3,토목공사,4,9.116667,12,36.466667
1,2,도시건축종합건설(주),재동 32-10 근린생활시설 신축공사,서울특별시 종로구 재동 32-10,37.579241,126.984249,서울특별시 종로구 재동 32-10,37.579241,126.984249,서울특별시 종로구,...,건설업,2024,7,2023,6,건축공사,3,6.066667,12,18.200000
2,6,(주)서우건설산업,2023년 능동로 가로등 개량공사,서울특별시 광진구 중곡동 158-7~중곡동16,37.557647,127.080876,서울특별시 광진구 중곡동 158-7~중곡동16,37.557647,127.080876,서울특별시 광진구,...,건설업,2023,11,2023,5,토목공사,4,7.083333,11,25.972222
3,7,보형포장건설(주),수출의다리~독산역일대 노후도로 정비공사,서울특별시 금천구 벚꽃로 244(가산동),37.476690,126.885808,서울특별시 금천구 가산동 60-73 ~독산동 1001-14 도로,37.476690,126.885808,서울특별시 금천구,...,건설업,2023,6,2023,3,기타공사,2,9.116667,6,9.116667
4,9,홍대 및 경의선숲길 주변 도로정비공사,홍대 및 경의선숲길 주변 도로정비공사,서울특별시 마포구 성미산로 112 (연남동),37.562062,126.919576,서울특별시 마포구 연남동 504-1,37.562062,126.919576,서울특별시 마포구,...,X,2023,5,2023,5,개발공사,4,7.083333,5,11.805556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,1579,대창종합건설(주),한국건강관리협회 서울서부지부 행정동 건립 신축공사,서울특별시 강서구 화곡로59길 13 (화곡동),37.554116,126.850324,서울특별시 강서구 화곡동 1098,37.554077,126.850438,서울특별시 강서구,...,X,2023,12,2023,12,건축공사,3,-0.033333,12,0.100000
1002,1582,(주)드림라인,"(서부지사 노후 열수송관 교체공사(등촌, 방화2))",등촌동 709-7/709-13/709-10,37.562379,126.843356,등촌동 709-7/709-13/709-10,37.562379,126.843356,서울특별시 강서구,...,X,2023,11,2023,11,개발공사,4,0.983333,11,3.605556
1003,1583,"서초동 1694-7,12번지 빌딩 신축공사","서초동1694-7, 12번지 빌딩 신축공사","서초동 1694-7,12",37.495185,127.013923,"서초동 1694-7,12",37.495185,127.013923,서울특별시 서초구,...,X,2025,6,2023,11,건축공사,3,0.983333,12,2.950000
1004,1584,통신관 매설공사,통신관 매설공사,서초동 1748-15번지 일원,37.487817,127.009720,서초동 1748-15번지 일원,37.487817,127.009720,서울특별시 서초구,...,X,2023,11,2023,11,기타공사,2,0.983333,11,1.802778
1005,1592,송도건설(주),조선왕릉 내 부적합시설물(개선관) 철거공사,서울특별시 노원구 공릉2동 산223-19 외 5필지,37.636216,127.097459,서울특별시 노원구 공릉2동 산223-19 외 5필지,37.636216,127.097459,서울특별시 노원구,...,건설업,2024,5,2023,8,건축공사,3,4.033333,12,12.100000

In [306]:
d['공사장_지수']

0       36.466667
1       18.200000
2       25.972222
3        9.116667
4       11.805556
          ...
1001     0.100000
1002     3.605556
1003     2.950000
1004     1.802778
1005    12.100000
Name: 공사장_지수, Length: 1006, dtype: float64

In [308]:
d.to_csv('공사장_지수.csv', encoding = 'cp949', index=False)

교통속도에 관련된 지수

In [261]:
speed.head(7)

,일자,요일,도로명,링크아이디,시점명,종점명,방향,거리,차선수,기능유형구분,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,20230101,일,4.19로,1080012200,아카데미하우스,국립4.19묘지,상행,1179,1.0,보조간선도로,...,29.24,21.88,30.72,33.23,32.04,35.90,30.01,48.15,48.96,51.71
1,20230101,일,4.19로,1080012800,국립4.19묘지,국립4.19묘지입구,상행,352,2.0,보조간선도로,...,11.31,10.21,12.62,13.05,15.18,14.19,17.00,16.30,12.33,13.87
2,20230101,일,4.19로,1080012700,국립4.19묘지입구,국립4.19묘지,하행,354,2.0,보조간선도로,...,12.81,17.11,17.26,16.67,20.01,17.97,18.43,21.74,21.29,17.85
3,20230101,일,4.19로,1080012100,국립4.19묘지,아카데미하우스,하행,1190,1.0,보조간선도로,...,44.42,44.91,63.47,62.30,48.73,51.30,46.97,50.32,52.08,40.54
4,20230101,일,가락로,1230024700,방이초교,방이동고분군,상행,844,1.0,기타도로,...,13.93,13.88,20.42,16.39,14.61,15.89,17.63,17.56,15.13,16.90
5,20230101,일,가락로,1230019500,방이동고분군,송파한양아파트,상행,416,1.0,기타도로,...,20.21,22.87,19.02,20.38,21.81,17.85,20.46,22.76,21.89,26.09
6,20230101,일,가락로,1230016300,송파한양아파트,송파사거리,상행,478,1.0,기타도로,...,20.05,21.96,19.32,19.75,18.93,19.33,20.25,20.85,27.01,20.16

In [249]:
speed.groupby(['시점명'])[['일자']].count().reset_index().to_csv('시점명.csv', encoding = 'utf-8', index =False)
speed.groupby(['종점명'])[['일자']].count().reset_index().to_csv('종점명.csv', encoding = 'utf-8', index =False)

In [22]:
traffic = pd.read_csv('traffic_cnt.csv', encoding = 'cp949');traffic

,Unnamed: 0,지점명,방향,교통량,year,month,위도,경도
0,0,가양대교,유입,1641095.0,2024,1,37.571567,126.862726
1,1,가양대교,유출,1464782.0,2024,1,37.571567,126.862726
2,2,강남대로(강남역-신분당),유입,724579.0,2024,1,37.490590,127.031160
3,3,강남대로(강남역-신분당),유출,780415.0,2024,1,37.490590,127.031160
4,4,강남대로(신사역),유입,1057444.0,2024,1,37.514859,127.020098
...,...,...,...,...,...,...,...,...
267,267,화랑로(상월곡역),유출,904675.0,2024,1,37.603932,127.044044
268,268,화랑로(조선왕릉),유입,645108.0,2024,1,37.630725,127.098984
269,269,화랑로(조선왕릉),유출,668135.0,2024,1,37.630725,127.098984
270,270,화랑로(화랑대역),유입,911202.0,2024,1,37.619936,127.082950
271,271,화랑로(화랑대역),유출,990316.0,2024,1,37.619936,127.082950

In [49]:
traffic = traffic.groupby(['지점명']).agg({'교통량':'sum','위도':'mean','경도':'mean','year':'mean','month':'mean'}).reset_index()
traffic.to_csv('교통량_예시.csv', encoding = 'cp949', index=False)

KeyError: "Column(s) ['경도', '교통량', '위도'] do not exist"

In [50]:
traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99280 entries, 0 to 99279
Data columns (total 38 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   일자      99280 non-null  int64
 1   요일      99280 non-null  object
 2   지점명     99280 non-null  object
 3   지점번호    99280 non-null  object
 4   방향      99280 non-null  object
 5   구분      99280 non-null  object
 6   0시      79624 non-null  float64
 7   1시      79632 non-null  float64
 8   2시      79693 non-null  float64
 9   3시      79618 non-null  float64
 10  4시      79643 non-null  float64
 11  5시      79681 non-null  float64
 12  6시      79718 non-null  float64
 13  7시      79700 non-null  float64
 14  8시      79687 non-null  float64
 15  9시      79761 non-null  float64
 16  10시     79753 non-null  float64
 17  11시     79770 non-null  float64
 18  12시     79783 non-null  float64
 19  13시     79771 non-null  float64
 20  14시     79792 non-null  float64
 21  15시     79815 non-null  float64
 22  16시     79840 non-null  float64
 23  17시     79891 non-null  float64
 24  18시     79923 non-null  float64
 25  19시     79921 non-null  float64
 26  20시     79917 non-null  float64
 27  21시     79897 non-null  float64
 28  22시     79692 non-null  float64
 29  23시     79609 non-null  float64
 30  요일(2)   8160 non-null   object
 31  날짜      99280 non-null  datetime64[ns]
 32  month   99280 non-null  int32
 33  year    99280 non-null  int32
 34  위도_x    99280 non-null  float64
 35  경도_x    99280 non-null  float64
 36  위도_y    99280 non-null  float64
 37  경도_y    99280 non-null  float64
dtypes: datetime64[ns](1), float64(28), int32(2), int64(1), object(6)
memory usage: 28.0+ MB

In [32]:
p = pd.read_excel('교통량.xlsx')
p.dropna().reset_index(drop=True).to_csv("교통량_마무리.csv", encoding = 'cp949',index = False)

In [45]:
code_cnt = code.copy()
code_cnt = code_cnt[['지점명칭','위도','경도']]
code_cnt.rename(columns = {'지점명칭':'지점명'}, inplace=True)

In [48]:
traffic = traffic.merge(code_cnt, on = '지점명');traffic.head(3)

,일자,요일,지점명,지점번호,방향,구분,0시,1시,2시,3시,...,22시,23시,요일(2),날짜,month,year,위도_x,경도_x,위도_y,경도_y
0,20230101,일,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,564.0,414.0,268.0,208.0,...,552.0,421.0,NaN,2023-01-01 00:01:00,1,2023,37.568588,126.948436,37.568588,126.948436
1,20230102,월,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,294.0,190.0,146.0,134.0,...,872.0,616.0,NaN,2023-01-02 00:01:00,1,2023,37.568588,126.948436,37.568588,126.948436
2,20230103,화,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,419.0,271.0,203.0,177.0,...,883.0,757.0,NaN,2023-01-03 00:01:00,1,2023,37.568588,126.948436,37.568588,126.948436

In [17]:
d = pd.read_csv('공사장_지수.csv', encoding = 'cp949') ;d[['Latitude','Longitude']]

       Latitude   Longitude
0     37.541624  126.971237
1     37.579241  126.984249
2     37.557647  127.080876
3     37.476690  126.885808
4     37.562062  126.919576
...         ...         ...
1001  37.554116  126.850324
1002  37.562379  126.843356
1003  37.495185  127.013923
1004  37.487817  127.009720
1005  37.636216  127.097459

[1006 rows x 2 columns]

교통 속도에 대한 데이터 전처리

In [57]:
speed01 = pd.read_excel('2023_차속도_1월.xlsx')
speed02 = pd.read_excel('2023_차속도_2월.xlsx')
speed03 = pd.read_excel('2023_차속도_3월.xlsx')
speed04 = pd.read_excel('2023_차속도_4월.xlsx')
speed05 = pd.read_excel('2023_차속도_5월.xlsx')
speed06 = pd.read_excel('2023_차속도_6월.xlsx')
speed07 = pd.read_excel('2023_차속도_7월.xlsx')
speed08 = pd.read_excel('2023_차속도_8월.xlsx')
speed09 = pd.read_excel('2023_차속도_9월.xlsx')
speed10 = pd.read_excel('2023_차속도_10월.xlsx')
speed11 = pd.read_excel('2023_차속도_11월.xlsx')
speed12 = pd.read_excel('2023_차속도_12월.xlsx')

In [58]:
speed = pd.concat([speed01,speed02,speed03,speed04,speed05,speed06,speed07,speed08,speed09,speed10,speed11,speed12],axis = 0)

In [59]:
geocode_start = pd.read_excel('시점명.xlsx')
geocode_end = pd.read_excel('종점명.xlsx')
geocode_start.drop("일자", axis = 1, inplace=True)
geocode_end.drop("일자", axis = 1, inplace=True)

In [60]:
speed = speed.merge(geocode_start, on = '시점명')
speed.rename(columns = {'Latitude':'Latitude_start','Longitude':'Longitude_start'}, inplace = True)
speed = speed.merge(geocode_end,on = '종점명')
speed.rename(columns = {'Latitude':'Latitude_end','Longitude':'Longitude_end'}, inplace = True)
sp = speed[(speed['Latitude_start'].isnull() == False) | (speed['Latitude_end'].isnull() == False)]
sp['speed_mean'] = sp[['01시', '02시', '03시', '04시', '05시', '06시', '07시', '08시', '09시', '10시', '11시', '12시', '13시', '14시', '15시', '16시', '17시', '18시', '19시', '20시', '21시', '22시', '23시', '24시']].mean(axis=1)
sp = sp[['도로명','방향','거리','차선수','Latitude_start','Longitude_start','Latitude_end','Longitude_end','speed_mean']]
sp[['Latitude_start','Longitude_start','Latitude_end','Longitude_end']] = sp[['Latitude_start','Longitude_start','Latitude_end','Longitude_end']].fillna("0")

C:\Users\kyj93\AppData\Local\Temp\ipykernel_26384\489329729.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sp['speed_mean'] = sp[['01시', '02시', '03시', '04시', '05시', '06시', '07시', '08시', '09시', '10시', '11시', '12시', '13시', '14시', '15시', '16시', '17시', '18시', '19시', '20시', '21시', '22시', '23시', '24시']].mean(axis=1)

In [61]:
sp[['Latitude_start','Longitude_start']] =  sp[['Latitude_start','Longitude_start']].replace({'Latitude': 0, 'Longitude' :0})
sp[['Latitude_end','Longitude_end']] =  sp[['Latitude_end','Longitude_end']].replace({'Latitude': 0, 'Longitude' :0})
sp[['Latitude_start','Longitude_start']] = sp[['Latitude_start','Longitude_start']].astype(float)
sp[['Latitude_end','Longitude_end']] = sp[['Latitude_end','Longitude_end']].astype(float)
sp['Latitude_start1'] = sp.apply(lambda x: x['Latitude_start'] if x['Latitude_start'] != 0  else x['Latitude_end'], axis=1)
sp['Longitude_start1'] = sp.apply(lambda x: x['Longitude_start'] if x['Longitude_start'] != 0 else x['Longitude_end'], axis=1)

sp['Latitude_end1'] = sp.apply(lambda x: x['Latitude_end'] if x['Latitude_end'] != 0  else x['Latitude_start'], axis=1)
sp['Longitude_end1'] = sp.apply(lambda x: x['Longitude_end'] if x['Longitude_end'] != 0 else x['Longitude_start'], axis=1)

sp['Latitude']  = sp.apply(lambda x: (x['Latitude_start1'] + x['Latitude_end1']) / 2 , axis=1)
sp['Longitude'] = sp.apply(lambda x: (x['Longitude_start1'] + x['Longitude_end1']) / 2, axis=1)
speed_final = sp.copy() ;speed_final

,도로명,방향,거리,차선수,Latitude_start,Longitude_start,Latitude_end,Longitude_end,speed_mean,Latitude_start1,Longitude_start1,Latitude_end1,Longitude_end1,Latitude,Longitude
0,4.19로,상행,1179,1.0,37.640402,127.001398,37.648496,127.007660,38.673750,37.640402,127.001398,37.648496,127.007660,37.644449,127.004529
1,4.19로,상행,1179,1.0,37.640402,127.001398,37.648496,127.007660,41.226667,37.640402,127.001398,37.648496,127.007660,37.644449,127.004529
2,4.19로,상행,1179,1.0,37.640402,127.001398,37.648496,127.007660,39.794583,37.640402,127.001398,37.648496,127.007660,37.644449,127.004529
3,4.19로,상행,1179,1.0,37.640402,127.001398,37.648496,127.007660,40.422083,37.640402,127.001398,37.648496,127.007660,37.644449,127.004529
4,4.19로,상행,1179,1.0,37.640402,127.001398,37.648496,127.007660,40.870000,37.640402,127.001398,37.648496,127.007660,37.644449,127.004529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676153,흑석로,상행,55,2.0,37.508533,126.964259,37.506224,126.956958,13.535000,37.508533,126.964259,37.506224,126.956958,37.507379,126.960609
1676154,흑석로,상행,55,2.0,37.508533,126.964259,37.506224,126.956958,14.647083,37.508533,126.964259,37.506224,126.956958,37.507379,126.960609
1676155,흑석로,상행,55,2.0,37.508533,126.964259,37.506224,126.956958,14.888333,37.508533,126.964259,37.506224,126.956958,37.507379,126.960609
1676156,흑석로,상행,55,2.0,37.508533,126.964259,37.506224,126.956958,15.457500,37.508533,126.964259,37.506224,126.956958,37.507379,126.960609
1676157,흑석로,상행,55,2.0,37.508533,126.964259,37.506224,126.956958,14.110000,37.508533,126.964259,37.506224,126.956958,37.507379,126.960609

In [62]:
speed_final = speed_final[['거리','차선수','Latitude','Longitude','speed_mean']]
speed_final['speed_mean_차선수_mul'] = speed_final.apply(lambda x: x['차선수'] * x['speed_mean'] if x['차선수'] != 0 else x['speed_mean'], axis = 1)

C:\Users\kyj93\AppData\Local\Temp\ipykernel_26384\463341483.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  speed_final['speed_mean_차선수_mul'] = speed_final.apply(lambda x: x['차선수'] * x['speed_mean'] if x['차선수'] != 0 else x['speed_mean'], axis = 1)

In [66]:
speed_final

           거리  차선수   Latitude   Longitude  speed_mean  speed_mean_차선수_mul
0        1179  1.0  37.644449  127.004529   38.673750           38.673750
1        1179  1.0  37.644449  127.004529   41.226667           41.226667
2        1179  1.0  37.644449  127.004529   39.794583           39.794583
3        1179  1.0  37.644449  127.004529   40.422083           40.422083
4        1179  1.0  37.644449  127.004529   40.870000           40.870000
...       ...  ...        ...         ...         ...                 ...
1676153    55  2.0  37.507379  126.960609   13.535000           27.070000
1676154    55  2.0  37.507379  126.960609   14.647083           29.294167
1676155    55  2.0  37.507379  126.960609   14.888333           29.776667
1676156    55  2.0  37.507379  126.960609   15.457500           30.915000
1676157    55  2.0  37.507379  126.960609   14.110000           28.220000

[1579910 rows x 6 columns]

In [67]:
speed_final.to_csv("speed_final.csv", encoding = 'cp949')

In [3]:
df = pd.read_csv('speed_final.csv', encoding = 'cp949') ;df

,Unnamed: 0,거리,차선수,Latitude,Longitude,speed_mean,speed_mean_차선수_mul
0,0,1179,1.0,37.644449,127.004529,38.673750,38.673750
1,1,1179,1.0,37.644449,127.004529,41.226667,41.226667
2,2,1179,1.0,37.644449,127.004529,39.794583,39.794583
3,3,1179,1.0,37.644449,127.004529,40.422083,40.422083
4,4,1179,1.0,37.644449,127.004529,40.870000,40.870000
...,...,...,...,...,...,...,...
1579905,1676153,55,2.0,37.507379,126.960609,13.535000,27.070000
1579906,1676154,55,2.0,37.507379,126.960609,14.647083,29.294167
1579907,1676155,55,2.0,37.507379,126.960609,14.888333,29.776667
1579908,1676156,55,2.0,37.507379,126.960609,15.457500,30.915000
1579909,1676157,55,2.0,37.507379,126.960609,14.110000,28.220000

구글에 있는 GeoCoding을 활용하기 위해 역명을 따로 분류

In [13]:
import pandas as pd
df = pd.read_csv('2023년_버스노선별_정류장별_시간대별_승하차_인원_정보(01월) - 2023년_버스노선별_정류장별_시간대별_승하차_인원_정보(01월).csv', encoding = 'utf-8');df

                        역명   Latitude   Longitude
0           종로2가사거리(00077)  37.569681  126.987763
1           종로2가사거리(00067)        NaN         NaN
2           종로2가사거리(00089)        NaN         NaN
3           종로2가사거리(00032)        NaN         NaN
4       창경궁.서울대학교병원(00031)        NaN         NaN
...                    ...        ...         ...
41057    김포교통(종점가상)(00081)        NaN         NaN
41058  구미동차고지(기점가상)(00001)        NaN         NaN
41059  구미동차고지(종점가상)(00062)        NaN         NaN
41060   가좌동종점(종점가상)(00078)        NaN         NaN
41061   가좌동종점(종점가상)(00127)        NaN         NaN

[41062 rows x 3 columns]

In [17]:
df = df[['역명']]
df.drop_duplicates().reset_index(drop=True).to_csv('버스정류장.csv', encoding = 'cp949', index =False)

In [4]:
import pandas as pd
bus = pd.read_csv('bus_stop.csv', encoding = 'utf-8');bus

      Unnamed: 0             역명
0              0        종로2가사거리
1              1    창경궁.서울대학교병원
2              2      명륜3가.성대입구
3              3       종로2가.삼일교
4              4  혜화동로터리.여운형활동터
...          ...            ...
8078        8078     김포교통(기점가상)
8079        8079     김포교통(종점가상)
8080        8080   구미동차고지(기점가상)
8081        8081   구미동차고지(종점가상)
8082        8082    가좌동종점(종점가상)

[8083 rows x 2 columns]

In [1]:
import pandas as pd
df = pd.read_excel('버스정류장.xlsx') ;df

      Unnamed: 0             역명   Latitude   Longitude
0              0        종로2가사거리  37.569681  126.987763
1              1    창경궁.서울대학교병원  37.578751  126.994878
2              2      명륜3가.성대입구  37.582720  126.998428
3              3       종로2가.삼일교  37.568715  126.987579
4              4  혜화동로터리.여운형활동터  37.586117  127.001626
...          ...            ...        ...         ...
8078        8078     김포교통(기점가상)  37.681823  126.626534
8079        8079     김포교통(종점가상)  37.681823  126.626534
8080        8080   구미동차고지(기점가상)  37.341960  127.105821
8081        8081   구미동차고지(종점가상)  37.341960  127.105821
8082        8082    가좌동종점(종점가상)  37.694838  126.721912

[8083 rows x 4 columns]

In [5]:
df.dropna().reset_index(drop = True).drop(columns = 'Unnamed: 0').to_csv('버스.csv', encoding = 'cp949', index = False)